---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bazarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: bazarr
      version: 10.5.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    image:
      repository: ghcr.io/k8s-at-home/bazarr
      tag: v1.1.0
    env:
      TZ: "${TIMEZONE}"
    ingress:
      main:
        enabled: true
        ingressClass: traefik
        annotations:
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          hajimari.io/enable: "false"
          hajimari.io/icon: "cloud-download"
        hosts:
          - host: bazarr.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - bazarr.${SECRET_DOMAIN}
            secretName: bazarr-tls
    persistence:
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "10.1.0.254"
            path: /volume1/Media/Library
      config:
        enabled: true
        existingClaim: bazarr-config-v1
