---
collections:
  - name: community.general
    version: 8.0.1
  - name: community.sops
    version: 1.3.0
  - name: ansible.posix
    version: 1.4.0
roles:
  - src: xanmanning.k3s
    version: v3.2.0
  - src: GROG.reboot
    version: v1.3.2
