---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homebridge
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: homebridge
      version: 4.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/oznu/homebridge
      tag: latest
    env:
      TZ: "America/Chicago"
      HOMEBRIDGE_CONFIG_UI: 1
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          hajimari.io/enable: "true"
          hajimari.io/icon: "resistor-nodes"
          hajimari.io/group: "automation"
        hosts:
          - host: "homebridge.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "homebridge.${SECRET_DOMAIN}"
            secretName: "homebridge-tls"
    service:
      main:
        type: LoadBalancer
    persistence:
      config:
        enabled: true
        existingClaim: homebridge-config-v1
        mountPath: "/homebridge"
