---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: radarr-uhd-http
  namespace: media
spec:
  jobName: radarr-uhd-http
  interval: 1m
  scrapeTimeout: 5s
  module: http_2xx
  prober:
    url: blackbox-exporter.monitoring:9115
  targets:
    staticConfig:
      static:
        - "http://radarr-uhd.media:7878"
        - "https://radarr-uhd.${SECRET_DOMAIN}"
