---
- name: install package dependencies
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - python3-pip
    - python-dev
    - python-setuptools
    - git
    - libyaml-dev
    - build-essential

- name: install virtualenv via pip
  ansible.builtin.pip:
    name:
      - virtualenv
    state: present
