---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k10
  namespace: kasten-io
spec:
  releaseName: k10
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.kasten.io/
      chart: k10
      version: 4.5.6
      sourceRef:
        kind: HelmRepository
        name: kasten-charts
        namespace: flux-system
      interval: 5m
  values:
    eula:
      accept: true
      company: STONEHEDGES-CT
      email: sean@obrienfamily.org
    global:
      persistence:
        storageClass: ceph-block
    auth:
      tokenAuth:
        enabled: true
    clusterName: stonehedges
    ingress:
      create: true
      annotations:
        external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        external-dns/is-public: "true"
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hajimari.io/enable: "true"
        hajimari.io/icon: "home-assistant"
      class: traefik
      host: "k10.${SECRET_DOMAIN}"
      urlPath: k10
      hosts:
        - "k10.${SECRET_DOMAIN}"
      tls:
        enabled: true
        secretName: "${SECRET_DOMAIN/./-}-tls"
    grafana:
      enabled: false
  postRenderers:
    - kustomize:
        patchesJson6902:
          - target:
              version: v1beta1
              kind: Ingress
              name: k10-ingress
            patch:
              - op: replace
                path: /apiVersion
                value: networking.k8s.io/v1
              - op: remove
                path: /spec/rules/0/http/paths/0/backend/servicePort
              - op: remove
                path: /spec/rules/0/http/paths/0/backend/serviceName
