# yamllint disable
# objstore.yml: |-
#   type: s3
#   config:
#     bucket:
#     endpoint:
#     access_key:
#     secret_key:
#     insecure: true
#
apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore
    namespace: monitoring
stringData:
    objstore.yml: ENC[AES256_GCM,data:qFQI8GEEXwckTMSf1qRqiZ1c/4loIdnLMrJsEjy+vQTms6xPlgNVjEqcdpFadFYD9La/p11T3fSiE3UsdOzfEWoAPKPlfd6j6w5AGSRutMxESrhFk1mmQCgOanOBeQFV4lCAAZPPqcVs8eetrWr4ONONl39SYSKWg25OLeqOZpZy+ly/5nUer2ekxl16KFvDXQB5h9mGMbiqRKclAGRuBcwfBhfz1kLFf/aYGQEx2FX9VEFVzCbH8EQWekywkNxcEXa16duJ4qM+GjTonghLjChLOPCB9H2cuN72FzIKBpmlxVNK6nzMe4pxmzMR6datKtU8y4hRI0GxrskQJG45IzoAVC25NA==,iv:cs/lKwDR85MOWcXwPn+8PAbeaQdKYh8dgi8ao0dVr+k=,tag:Lf/e6DQnP8Wn6KcRGszRAw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age179qz74lpav0lcywkjzujhnlu3ukq9kgz9jdxm2u59w47j337kc2q0e8q20
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUTGtpSDBDam5IaG51Tm5a
            dXQ5M2RrQzFQMjZXK2NFNTZBeXErSXJKMW1vCmpFTS92eWJaN2dVVWFYV3pESHMw
            bUo4TzFkSG1IZCs1WnB5YVhPeEdBQTQKLS0tIERBUHVkODJUb0pta053MFQrWStm
            QW1CVFRQYVhzSDdNLzBuVElvOWVKSlkK6sDaa0bbidjiTZ/7AsTpN6gvy3H8VXtV
            4+LMZu2Yf23Heup9E5qNoSnk9nReHxUeCZaVyHlZO+9+0Rhkt+1r9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-03T07:06:33Z"
    mac: ENC[AES256_GCM,data:Fr92ySLtiEKkUC9Asw9AIHyl7P1dwGqqY7qp5NZlVD7jPj1qBz6n4JaxajZ6/ZbtFm7iwlavt+ZXf9LX7nEexgK6hVMP+7/CrBQPJGEGm3Z23anhHIsxXon0tJH9bFU8zRTYQl+Rmkhb98m87yyf9qHuR2Zm1s4zC+3/nkILpaI=,iv:+kwnFZYr78i/QPuy38kuySA7cY1/JTck8GIoOiw8Pxo=,tag:m1ZIAkH0MSe0VgiMKZeIwg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
