# yamllint disable
# objstore.yml: |-
#   type: s3
#   config:
#     bucket:
#     endpoint:
#     access_key:
#     secret_key:
#     insecure: true
#
apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore
    namespace: monitoring
stringData:
    objstore.yml: ENC[AES256_GCM,data:jok8z3cM56pK5AYg/460aR+AKi4ZA5QMUeC+U6V1/Zb+xPNQ7kmiUjWk/HlANQiUWlSi2k6qXbwoDl35aHFIkqJ0le0psqidVB9yG5N5CG6vFBwJTU56A/r7UpLhx7jhAcd6qRnBA69FBsPrCpyJlZhzSffrsk9MNlURrV7oaUppoiQcBUqWuSwHWQdnCvHqvcnHgKTGFv4uGgFNwQ3lI9xYqeTFjy1XWa2J3XgZszF1Lz0PI1Fz6lhdjP9EChMFAWTXZ9zJ5kdnP7pcxCDrTabSs63Ucos8X9FdYW1DHWFFf5z8S6pHf/zK6uB2xDyAQA==,iv:ImUv0Uoi/MQq+jLT7RvEr2vq7VttO9WeJuueR/ZUTTk=,tag:nC1/mQSXVfLXfnt9jRlO7g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age179qz74lpav0lcywkjzujhnlu3ukq9kgz9jdxm2u59w47j337kc2q0e8q20
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6UTFSVHlpUlg5UlRnOE9V
            V2JDbnVjeTlVaGF2NER1NUxycDU1Y3Naa0VFCkFsdnRIaDZhS3VIckdXTHJ6QWN1
            aDQyUjYyWW5CNFNHUjlzNG9OSDd6SWMKLS0tIDNlZWdXZFE1b0xEc2VRZTZDbkZj
            enI1eG1rSldCK2k0d1ArZTJNSnk0eGsKq6400VHIeIuxBcMd9plhiUvjwnEojBuL
            fs5YKmmS97G9V4aexB5VBHmcjzzKwNmB7GVieoYR/ckR+kCfpaV7bQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-03T07:13:58Z"
    mac: ENC[AES256_GCM,data:pE1ruvHy1IqbLvzpLw2ClKJ41bGG+zyIPcPFyffkIlVzioY8nlhlSHynRPS4Rl0w3ifCJUkIjkEOzJHVFHYOiu0JzKjhFczrrluvCkAfJ9WUWABdW409iJKt5T1098kMsYfFA2fo1HYMTNQwK3c4KW4zUqvsnm6ZOHyBWzmbvkE=,iv:W0jGPiLizqS04E5MSV/qF1R8NFDT76IikUtogk7XASs=,tag:dJoZiuDJ7xHWCY2w5Pcf8g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
