---
- name: restart smartd
  ansible.builtin.service:
    name: smartd.service
    daemon_reload: true
    enabled: true
    state: restarted

- name: restart unattended-upgrades
  ansible.builtin.service:
    name: unattended-upgrades.service
    daemon_reload: true
    enabled: true
    state: restarted

- name: reload timesyncd ntp
  ansible.builtin.shell: timedatectl set-ntp false || true;
    timedatectl set-ntp true || true;

- name: reload timesyncd
  ansible.builtin.service:
    name: systemd-timesyncd
    state: reloaded

- name: restart timesyncd
  ansible.builtin.service:
    name: systemd-timesyncd
    state: restarted

- name: sync RTC
  ansible.builtin.command: timedatectl set-local-rtc 0
