---
- name: restart smartd
  ansible.builtin.service:
    name: smartd.service
    daemon_reload: true
    enabled: true
    state: restarted

- name: restart unattended-upgrades
  ansible.builtin.service:
    name: unattended-upgrades.service
    daemon_reload: true
    enabled: true
    state: restarted
