# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: code-server
    namespace: home
stringData:
    id_rsa: ENC[AES256_GCM,data:IajSh7X56zF3A6KFL4l4FcdsR/2abZ4HPQ71GjjN/l0YRpzMQS4nF0/vIIhG5TCVXPMf483ni2uYOP5/o0ZMM9HehEoJ1K3b04Rz2KU+K4w=,iv:79U697DXXuLXnRAzSR6e4j7ydLRNXIR0DxvfAdGYn8I=,tag:jzfhmC3eQIC4KvZbl6y0ew==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age179qz74lpav0lcywkjzujhnlu3ukq9kgz9jdxm2u59w47j337kc2q0e8q20
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpNkh2M0dSVHN5Y0VUdW9u
            NmNDTlFkcHVkeXg0K24rNWNIZkxyTlFaU2pzCkJJT3lqMDJDcXZic1J4dWp0S0tw
            MCtRQlpscW04TDlVdllwUllnTnF0eWsKLS0tIGxsMUtKUVl0TlZnZmE5QysyVGw1
            MDNtaU9NWW1jWFgyRitLcjU5NTNPMGsKIXBXp9ZzC4Quw5aG1sY7vysxJQARnKii
            p4xUeolLPpe63OzgqgVOxQXcKIG0PtgyB09oEZ96XuM0IvoXKBuyJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-02T05:34:35Z"
    mac: ENC[AES256_GCM,data:K6BApXn7FTKeHt0Dn3JC4fh1DdYLAQ6/AskuAjkSMRaAzl1SdZYUJKPgf8lH+/3Vn+1tgfmrxvqI3D3MwRKmb8Ee5kAVw6bG3Im6PxsqiC0do9gQ+pZWvtz33BeQuR5OWMR5HAJAWKdsv9CCWoTay6CZZGJ3nNTrYuQT75Ntxs8=,iv:j3XjU2xtup5Nx8eq+ed+vNMx1DaZg71U/dbrndpQ0NA=,tag:PDkzh7588qtiAbq5HNQFpg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
