# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: code-server
    namespace: home
stringData:
    id_rsa: ENC[AES256_GCM,data:6iB4cIFpGecPqYyV9s6/tMAJEmAJwtuHWBak4QoovaY0Gngfyrfqpq7nuPLhTeZq2BFO2mEqGQluWfIoVsoHRY3f9TWGY9Xbw46JOfVWCvAx7lR0MdpoJ+3qF5ER90yHppCmBPRvTgss5qaGdui/XJ+I1hfJ0QFex/z5EXSd+a3T52ZsBiDGGy9Ue9puIs6c28s1aBcYmFPUCeCOQyG/Hgj3AoObMILGpK5otGup+dmDmB3hGwDS2WimxYUZePW3wp9E5LI6BRInGtleQOZJuOLCun2JdNi9u3pqyG8AX0g72q8CTqF5GQLfQDKM/7mm1ljeE/5YCUoPaKrm9B94+U79i7QOewXjOgK4B45UDEUCPivDN9JQUmska/XYqKrlTNxoby1Z1bup8oWJ+7FgOtM0p2Lmnn/FiGFeYCr+IzUG4wVQN8cNKR+ZK9L85ImZwsPtcjRg79xIMPvukEK91nwqlp417YF0OARMLJ7w7FgdLOwcE9FKu42ddNVK9M406ACm+sD8QDLkSYXsb+/X,iv:qay5jtE8tV/Czn2nQh+iFeKyzRCo2wV+UPpqZh2CsVQ=,tag:lTaDgRbY0QlF0yIRcQAWrw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age179qz74lpav0lcywkjzujhnlu3ukq9kgz9jdxm2u59w47j337kc2q0e8q20
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYeDBwUjNKWGo0bnpXZzBM
            Z1YxSEtySFhCREY3NXRsb2R2S04xcllwV0NnCmFxcC9xa3Y1c2hFemd6amlNbVBX
            Q2V2cXBqNEFYV3VhZlo0blpEdTY5YkkKLS0tIDRRQnVMQkd4U2h6WjZsR3RWaFdJ
            cUtsb05GVTF1UVQzZDlORHNrVmxPWFEKNexcXV3vjxg5EYUrKXcUJbFlQpLR+eAJ
            18pbI9qz2GPuE1OWcpeGAk73/YOspNUR+UMTdt3AgVng/cguYfCuMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-02T06:13:49Z"
    mac: ENC[AES256_GCM,data:97/Nk/rKj99U+MyF8fL+zlUZj6sfUVSTObhKZJp43VjZReNEkEeqaNBBiO4ghV6YHu2SJDJ5GUNWQ1cvPsuGfgYR0ZtyhsB6Tw4ckcZ44I24nZy2GnHvjljX8RhoCGwBrQAjELRBTHt15jfEj91IDTDapdWppBQQSNfEYkx5q04=,iv:mz6cEklIRKHxH/IJx6SD4JTcbz+oufCVCqSKAaHxxBo=,tag:eB2ZT0d6ajV2pxE3SVt2aw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
