# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-influxdb
    namespace: home
stringData:
    user.name: ENC[AES256_GCM,data:AvNfsLiv8IUWSvl18zA=,iv:WjTOuGL0oQ5tVVkNgI/edwD3Gm7DGQa/RJriUjRVM6Q=,tag:6YSfTWNzrbFzb+Oswu6Sbw==,type:str]
    user.pwd: ENC[AES256_GCM,data:vuAi0iP0wmI9zF4/w0WXzw==,iv:dMte144huuai8ROS/YLqsuPL6/S6SS+/2gSHw7ou6Sk=,tag:p/0BOkEZ04vtXO5ujHoVbQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age179qz74lpav0lcywkjzujhnlu3ukq9kgz9jdxm2u59w47j337kc2q0e8q20
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGRGRNOUJhVXNzMWdtSnZI
            akxWZXNQVmhkUEdlSGVxa1FvMFB1L21QRWk4ClZhMkFKV1d1YmpIMkdudk9KR2VJ
            T09KZTNpSnF2VDFNVE1DcFVOMTZwYjQKLS0tIHo3bTQrRDF3cldlVW13Sld1czlT
            R3F0c1BXZU9wU1NMb3UwQnpNMUMvcjQKYZmbS3w5D0vERceC9TGHRXgQhs58O90b
            f9P30QB2/eoEXVRN4dbItFqRkivkxasETSX0v9Z58tlFJdCdde5EcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-02T19:05:21Z"
    mac: ENC[AES256_GCM,data:IK2vmHC6hbC59cCLqju8s/svrc8F72r3k7UTPmYYOzIRp9ihDEnUhwKyQxrmM7nGUSpWFr12v43Unuuya0UiA7QAxODKF0DRoFfEQ6bzca3fdRGZ0JUqLFsUDq9dvXgvCA+wtROACa39qvgThAnk5MbXM24r9cyAw6xIKHzfBeU=,iv:Cj6fXExVI7O5NVbTErpORpPaunSNWcn3TXdITHzOAoU=,tag:it3d8zEBuVKoTdZ+4VkrZw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
