---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - blackbox-exporter
  - botkube
  - goldilocks
  - grafana
  - kube-prometheus-stack
  - loki
  - snmp-exporter
  - speedtest-exporter
  - thanos
  - unifi-poller
  - uptimerobot-heartbeat
  - vector-agent
  - vpa
