---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: photoprism
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: photoprism
      version: 7.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    env:
      TZ: "${TIMEZONE}"
      PHOTOPRISM_STORAGE_PATH: /media/Library/photos
      PHOTOPRISM_ORIGINAL_PATH: /media/Library/photos-original
      PHOTOPRISM_PUBLIC: "true"
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          external-dns/cloudflare-proxied: "false"
          hajimari.io/enable: "false"
          hajimari.io/icon: "plex"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "photos.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "photos.${SECRET_DOMAIN}"
            secretName: photoprism-tls
    persistence:
      config:
        enabled: true
        existingClaim: photoprism-config-v1
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "10.1.0.104"
            path: /Media
        mountPath: /media
        readOnly: false
