---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: coredns
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://coredns.github.io/helm
      chart: coredns
      version: 1.16.5
      sourceRef:
        kind: HelmRepository
        name: coredns-charts
        namespace: flux-system
      interval: 5m
  values:
    replicaCount: 3
    serviceType: LoadBalancer
    prometheus:
      service:
        enabled: true
      monitor:
        enabled: true
    service:
      externalTrafficPolicy: Local
      loadBalancerIP: ${METALLB_COREDNS_ADDR}
      annotations:
        metallb.universe.tf/allow-shared-ip: coredns
    rbac:
      create: true
    isClusterService: false
    servers:
      - zones:
          - zone: ${SECRET_DOMAIN}.
            scheme: dns://
            use_tcp: false
          - zone: ${SECRET_PRIVATE_DOMAIN}.
            scheme: dns://
            use_tcp: false
        port: 53
        plugins:
          - name: errors
          - name: health
            configBlock: |-
              lameduck 5s
          - name: ready
          # - name: kubernetes
          #   parameters: cluster.local in-addr.arpa ip6.arpa
          #   configBlock: |-
          #     pods insecure
          #     fallthrough in-addr.arpa ip6.arpa
          #     ttl 30
          - name: prometheus
            parameters: 0.0.0.0:9153
          - name: forward
            parameters: . /etc/resolv.conf
          - name: cache
            parameters: 30
          - name: loop
          - name: reload
          - name: loadbalance
          - name: file
            parameters: /etc/coredns/${SECRET_DOMAIN}
          - name: file
            parameters: /etc/coredns/${SECRET_PRIVATE_DOMAIN}
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - coredns
              topologyKey: kubernetes.io/hostname
    zoneFiles:
      - filename: ${SECRET_DOMAIN}
        domain: ${SECRET_DOMAIN}
        contents: |
          ${SECRET_DOMAIN}.   IN SOA etta.ns.cloudflare.com. dns.cloudflare.com. 2020100600 10000 2400 604800 3600
          *.${SECRET_DOMAIN}. IN A ${METALLB_TRAEFIK_ADDR}
      - filename: ${SECRET_PRIVATE_DOMAIN}
        domain: ${SECRET_PRIVATE_DOMAIN}
        contents: |
          ${SECRET_PRIVATE_DOMAIN}.        IN SOA ns1-03.azure-dns.com. azuredns-hostmaster.microsoft.com 1 3600 300 2419200 300
          mordor.${SECRET_PRIVATE_DOMAIN}. IN A ${EXT_NAS_01_ADDR}
          gw.${SECRET_PRIVATE_DOMAIN}.     IN A ${EXT_GATEWAY_ADDR}
          stone-metal-01.${SECRET_DOMAIN}. IN A ${EXT_STONE_METAL_01_ADDR}
          stone-metal-02.${SECRET_DOMAIN}. IN A ${EXT_STONE_METAL_02_ADDR}
          stone-metal-03.${SECRET_DOMAIN}. IN A ${EXT_STONE_METAL_03_ADDR}
          stone-pdu-01.${SECRET_DOMAIN}.   IN A ${EXT_PDU_01_ADDR}
          stone-ups-01.${SECRET_DOMAIN}.   IN A ${EXT_UPS_01_ADDR}
          hue-bridge-01.${SECRET_DOMAIN}.  IN A ${EXT_HUE_BRIDGE_01_ADDR}
          stone-maas.${SECRET_DOMAIN}.     IN A ${EXT_STONE_MAAS_ADDR}
