---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: teslamate
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: teslamate
      version: 6.5.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: teslamate/teslamate
      tag: 1.25.0
    env:
      TZ: "${TIMEZONE}"
      MQTT_HOST: "mosquitto.home"
      MQTT_USERNAME: "mqtt"
    ingress:
      main:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          hajimari.io/enable: "true"
          hajimari.io/icon: "resistor-nodes"
          hajimari.io/group: "automation"
        hosts:
          - host: "tesla.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "tesla.${SECRET_DOMAIN}"
            secretName: tesla-tls
    persistence:
      import:
        enabled: true
        existingClaim: teslamate-v1
    resources:
      requests:
        memory: 250Mi
        cpu: 50m
      limits:
        memory: 500Mi
    probes:
      liveness:
        spec:
          periodSeconds: 10
          failureThreshold: 15
      readiness:
        spec:
          failureThreshold: 15
          periodSeconds: 10
      startup:
        spec:
          initialDelaySeconds: 15
          failureThreshold: 30
          periodSeconds: 10
    postgresql:
      enabled: true
      persistence:
        enabled: true
        existingClaim: teslamate-postgresql-v2
  valuesFrom:
    - kind: Secret
      name: "teslamate-helm-values"
      optional: false
