# yamllint disable
# values.yaml: |
#   MQTT_USERNAME: ${SECRET_MQTT_USERNAME}
#   MQTT_PASSWORD: ${SECRET_MQTT_PASSWORD}
#   POSTGRES_USERNAME: teslamate
#   POSTGRES_PASSWORD: ${SECRET_TESLAMATE_POSTGRESPASS}
#
kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: teslamate-helm-values
    namespace: home
stringData:
    values.yaml: ENC[AES256_GCM,data:ppEG0j5WCUieUrkgO5Wzw99dKqEBHXyk6TnrFhIrGAP/cDfS7hqRrzc7n4EYnhYtieEbTy/Nw6DNpaLJ8gABvlTDCeXzqMZmAaqTJPnnw1mzmFSs2suBIDCx46Mjv6UWjBN9tpfiG1nPbEtN7bh4MreD2pyOAJ8cVg9GihNBnpkicdgpX1ycezY4f0z/MIAq8MDGGu683Bo/8YSWeNvS,iv:E2cTBg4gRMipD3AkSnVQrPH4vkqNMT+P0L0lzXjYpq0=,tag:Xe1J7urMRv+b8D7w/3xbxw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age179qz74lpav0lcywkjzujhnlu3ukq9kgz9jdxm2u59w47j337kc2q0e8q20
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXMFhxZndGNnBPTTZqamly
            Y2t4dkoreHdaRWlhR3F0eGhSZStqTXFvclRjCkxtMmZsajdEdEE4ZGtWaU5jeWo2
            U2NlNDdDKzNzL3lUWlB0TXZtOGt3RjgKLS0tIEp0T1kzSktKTzRFVldNdFpWbHk4
            RVF3K01MYnIrRU9vMHk2bHNIY01HemMKXftSu5d6rg1Ew8NTh5rR5q2FqncsC50M
            /bzw7oeD7psbpgzxtr1prJWxom/fv+bIU9E7oY9HUBntcSBE5WVBdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-10T21:34:59Z"
    mac: ENC[AES256_GCM,data:y4Y8FRbPGm7ki/mrCmhhhHQRHYPKppYdjWQYpDT6sU5L4MDOVS50eXFnB8xPGYtykVFMlHrHEM3m1uOzW65vjdUGt7d7T5ANeA6Bm1H7IOqgyPbt7X3UVJoxCcZiSn5zUCCN0kYzUowEJC3fccLzIjzyf6uwhDwTGqS1kbT8knU=,iv:OonzFuB97CkaSxKQVhoRPy6ACEXjuMRZugag4UMnJWE=,tag:T7jVPvh2v+nymuazzHcdow==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
