---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blocky
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: blocky
      version: 10.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/0xerr0r/blocky
      tag: v0.17
    controller:
      strategy: RollingUpdate
      replicas: 1
    env:
      TZ: "${TIMEZONE}"
    service:
      main:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: "${METALLB_BLOCKY_ADDR}"
        ports:
          http:
            port: 4000
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/allow-shared-ip: blocky
      dns-tcp:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: "${METALLB_BLOCKY_ADDR}"
        ports:
          dns-tcp:
            enabled: true
            port: 53
            protocol: TCP
            targetPort: 53
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/allow-shared-ip: blocky
      dns-udp:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: "${METALLB_BLOCKY_ADDR}"
        ports:
          dns-udp:
            enabled: true
            port: 53
            protocol: UDP
            targetPort: 53
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/allow-shared-ip: blocky
    metrics:
      enabled: true
      serviceMonitor:
        interval: 30s
        scrapeTimeout: 10s
      prometheusRule:
        enabled: true
    podAnnotations:
      configmap.reloader.stakater.com/reload: "blocky-config"
    persistence:
      whitelists:
        enabled: true
        mountPath: /app/whitelists
        type: custom
        volumeSpec:
          configMap:
            name: blocky-whitelist
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - blocky
              topologyKey: kubernetes.io/hostname
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 750Mi
    config: |
      bootstrapDns: tcp+udp:1.1.1.1
      upstream:
        default:
          - tcp-tls:${SECRET_NEXTDNS_ID}.dns.nextdns.io
          - https://dns.nextdns.io/${SECRET_NEXTDNS_ID}
      conditional:
        mapping:
          status.${SECRET_DOMAIN}: tcp+udp:1.1.1.1
          ${SECRET_DOMAIN}: tcp+udp:${METALLB_COREDNS_ADDR}
      blocking:
        blackLists:
          ads:
            - https://raw.githubusercontent.com/ookangzheng/dbl-oisd-nl/master/dbl.txt
            - |
              /^ad([sxv]?[0-9]*|system)[_.-]([^.[:space:]]+\.){1,}|[_.-]ad([sxv]?[0-9]*|system)[_.-]/
              /^(.+[_.-])?adse?rv(er?|ice)?s?[0-9]*[_.-]/
              /^(.+[_.-])?telemetry[_.-]/
              /^adim(age|g)s?[0-9]*[_.-]/
              /^adtrack(er|ing)?[0-9]*[_.-]/
              /^advert(s|is(ing|ements?))?[0-9]*[_.-]/
              /^aff(iliat(es?|ion))?[_.-]/
              /^analytics?[_.-]/
              /^banners?[_.-]/
              /^beacons?[0-9]*[_.-]/
              /^count(ers?)?[0-9]*[_.-]/
              /^mads\./
              /^pixels?[-.]/
            - https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
            - http://sysctl.org/cameleon/hosts
            - https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
          kids:
            - https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn/hosts
          none:
        whiteLists:
          ads:
            - https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt
        clientGroupsBlock:
          default:
            - ads
      clientLookup:
        upstream: tcp+udp:1.1.1.1
      prometheus:
        enable: true
        path: /metrics
      httpPort: 4000
      logFormat: json
      logLevel: info
