---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: overseerr-http
  namespace: media
spec:
  jobName: overseerr-http
  interval: 1m
  scrapeTimeout: 5s
  module: http_2xx
  prober:
    url: blackbox-exporter.monitoring:9115
  targets:
    staticConfig:
      static:
        - "http://overseerr.media:5055"
        - "https://requests.${SECRET_DOMAIN}"
