---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: unifi-browser
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: /charts/kah-common/
      sourceRef:
        kind: GitRepository
        name: flux-cluster
        namespace: flux-system
      interval: 5m
  values:
    fullnameOverride: unifi-browser
    image:
      repository: docker.io/sobrien/unifibrowser
      tag: latest
    env:
      NOAPIBROWSERAUTH: 1
      DISPLAYNAME: STONEHEDGES
    service:
      main:
        ports:
          http:
            port: 8000
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          hajimari.io/enable: "true"
          hajimari.io/icon: "resistor-nodes"
          hajimari.io/group: "automation"
        hosts:
          - host: "unifi-browser.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "unifi-browser.${SECRET_DOMAIN}"
            secretName: unifi-browser-tls
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 750Mi
  valuesFrom:
    - kind: Secret
      name: "unifi-browser-helm-values"
      optional: false
