---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: sonarr-uhd-http
  namespace: media
spec:
  jobName: sonarr-uhd-http
  interval: 1m
  scrapeTimeout: 5s
  module: http_2xx
  prober:
    url: blackbox-exporter.monitoring:9115
  targets:
    staticConfig:
      static:
        - "http://sonarr-uhd.media:8989"
        - "https://sonarr-uhd.${SECRET_DOMAIN}"
