---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: tautulli-http
  namespace: media
spec:
  jobName: tautulli-http
  interval: 1m
  scrapeTimeout: 5s
  module: http_2xx
  prober:
    url: blackbox-exporter.monitoring:9115
  targets:
    staticConfig:
      static:
        - "http://tautulli.media:8181"
        - "https://tautulli.${SECRET_DOMAIN}"
