# yamllint disable
# values.yaml: |
#   env:
#     AK_ADMIN_PASS: "${SECRET_AUTHENTIK_ADMIN_PASS}"
#     POSTGRES_PASSWORD: "${SECRET_AUTHENTIK_POSTGRES_PASS}"
#     AUTHENTIK_SECRET_KEY: "${SECRET_AUTHENTIK_KEY}"
#     AUTHENTIK_COOKIE_DOMAIN: ".${SECRET_DOMAIN}"
#     AUTHENTIK_EMAIL__HOST:
#     AUTHENTIK_EMAIL__PORT:
#     AUTHENTIK_EMAIL__USERNAME:
#     AUTHENTIK_EMAIL__PASSWORD:
#     AUTHENTIK_EMAIL__USER_TLS: "true"
#     AUTHENTIK_EMAIL__USER_SSL: "true"
#     AUTHENTIK_EMAIL__FROM: "login@${SECRET_DOMAIN}"
#     AUTHENTIK_FOOTER_LINKS: "[]"
#
kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: authentik-helm-values
    namespace: authentik
stringData:
    values.yaml: ENC[AES256_GCM,data:GtFykVmQQWW9rGgqYO8D5KQhEQgtbzqhKfcMoDjq9ZjJnoR642fG/x+w4XP+CdOQr3wgvgQ2+TymQwDEGRjfk6I6L/VuTi7QHbVxtb+qXJmEQ/QtojpNMeze6dxroMbBC9Upbzf/YvFeFMnu+0bbiYZVyn6FM2tuJwEWKAFSnPa6QIy8yrdn5ZHTsetfmhjDjp8uYOgs0pwVbKnurqPk3xJKhXB3+brpHjd9UDRwHyPP5HVLgmqWP+Ee9PJtrobKIihto7POphWVnKvnnguS7eBq6r4cdPpqKYWLdPjSTBmXdOfT5LBLT9HSd1mOzLWbgFVgNNtixYJXjppQWlspcd1q4EME0JhohoyZwasXo7cv6r8GlWP0vVWqcMYLjxCLFi2YnFaDvV005htC7K1pT/IAW0U7vKmEUnW1RTIzDJbRo2b5s62TnHB9RyBhh2/F/LjnjgPXJDMqyCSfvJCEDw2RBrorAPVTY7kzfYPIxPw6qOT1070faylGl0QSznwHt+mukCweHtb4CfPnYqdgYjFBYPQCnjRd2vrpi6rPSYbOb3YnDwsQSLyrq86tlijR1fJyexIUq9tvqIpEEVDtNvCNKeKyhHpMKyyRl4IcECw11oqCDDYBwzAt7bvPAjOuQVwerNmWIeWgKNr8TGkDIoZhkFkdaJhKW5oXoVEZCBuUspEOmVoJ5zuNixS9RsLIq0LXeQ==,iv:s0BE9RN1DKgpw+bQQIUdIcxaj8EU3UbJ3WL8mGJtSIk=,tag:U5XdksWjhDrNJUZxTo2D5g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age179qz74lpav0lcywkjzujhnlu3ukq9kgz9jdxm2u59w47j337kc2q0e8q20
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZVcwdjJmTHpYQkhUR2h0
            MmN3SllZUnZuaGYySmVjcTV5YjZ5aDdUREFRClUxaUdsOXNMNkFyVWlrdC9yekpU
            T1JzSm5FTGF5UkdCRmR5TFp1d3hlYUUKLS0tIHBQUTNIZ2ZCdzBpNHJLSEFOdmxQ
            d3VIZU4zT2hKWmVPL2lFWUhpTnAxWTQKcM17yrv/73/LzY+4LMpfqc6utYXt9Uqk
            XKC+RtDEwAOyTfzMgGykyaFFVIrM3ESIpnac238eXbs0KdQ+Wxg0MQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-26T22:53:08Z"
    mac: ENC[AES256_GCM,data:07C2JRLPzLk91QtNUCI/y4zK5oSihsf8eEtT3By9cDTvJ69qcDS8ewafVYPiiZjKj8KYmid1HdOP8kv/LHz/wdU4FW/B1N6fHLDUeu/xWrduhlX+5cLVSQF0anB3Vc9rbUg4R1BADV7TPt3L5BjFNamcw2zU44ua91tMHRxIs7g=,iv:HmAr5SiUxqU+xsx3kcBYEDKJgJRQrFagCYoLaNf9XaM=,tag:N6aJ4Rt+HaWgVzORYUwcIQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
