# yamllint disable
# values.yaml: |
#   env:
#     AK_ADMIN_PASS: "${SECRET_AUTHENTIK_ADMIN_PASS}"
#     POSTGRES_PASSWORD: "${SECRET_AUTHENTIK_POSTGRES_PASS}"
#     AUTHENTIK_SECRET_KEY: "${SECRET_AUTHENTIK_KEY}"
#     AUTHENTIK_COOKIE_DOMAIN: ".${SECRET_DOMAIN}"
#     AUTHENTIK_EMAIL__HOST:
#     AUTHENTIK_EMAIL__PORT:
#     AUTHENTIK_EMAIL__USERNAME:
#     AUTHENTIK_EMAIL__PASSWORD:
#     AUTHENTIK_EMAIL__USER_TLS: "true"
#     AUTHENTIK_EMAIL__USER_SSL: "true"
#     AUTHENTIK_EMAIL__FROM: "login@${SECRET_DOMAIN}"
#     AUTHENTIK_FOOTER_LINKS: "[]"
#
kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: authentik-helm-values
    namespace: home
stringData:
    values.yaml: ENC[AES256_GCM,data:q5VAL5VRkUa57MSSpLUHwXdd6pQNYwTbQL8j1t1ZWJr1WFAcs8QySsKf2MbQ5c7lsGdUJHATjTsLOJM9XsyaeLPmUL5wJqM4OVHJqLuhrbguW17on9IGnblc242+KlfWOt3T/BQDf89/g5xMbCtA9Qo1cFLDjCCXiafHDIAOeSCA5sCC27reeuQdJRKu8jmyqF4NwLvnr9I9sXQL8lJwapZ3Q5h+ubtYuhBRgT67Rk1xHC7K7Zn6Mkpw+B1kvEMyLcBB0B/uznr3TLEUJ+iDfZr4llsGdJee0X7jYgBfnAAWLmMhO6YgzUatCfbLqksa1/ZA4CWYzX8HCB7HdYwPHTy510lKW625IY32XUQ7D5Ir2OWSH6rX9v9siU3/OA0/Cg6yrD6+c1jvcyAIhPvfhfcgq6aEBeWCwKBv8dQ4n1RIBQl+4QVlMvEJOsdbtBntsmjO5mILXX5GjYd8bD+lHicO6dsc+5UYSGq1VmFHsorwgZMPuOnpeuJNsd4lXmKTXVShDsOu1qvDZkqreFPFilMnwyyaPI0soP9fNebyZ9AzO6zbx1Q7T7H58Kardua2myNO1OzZR6zMLi6DJa2195HZsESb+tC1h49RR1WwZTz6wd5NaFA=,iv:t4zHFUCyIAC1BUEv19w7PtfrOLlBgcwRtEMqVYmReDU=,tag:fdU3W6xUQ0hTVpe1pjRobA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age179qz74lpav0lcywkjzujhnlu3ukq9kgz9jdxm2u59w47j337kc2q0e8q20
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZVcwdjJmTHpYQkhUR2h0
            MmN3SllZUnZuaGYySmVjcTV5YjZ5aDdUREFRClUxaUdsOXNMNkFyVWlrdC9yekpU
            T1JzSm5FTGF5UkdCRmR5TFp1d3hlYUUKLS0tIHBQUTNIZ2ZCdzBpNHJLSEFOdmxQ
            d3VIZU4zT2hKWmVPL2lFWUhpTnAxWTQKcM17yrv/73/LzY+4LMpfqc6utYXt9Uqk
            XKC+RtDEwAOyTfzMgGykyaFFVIrM3ESIpnac238eXbs0KdQ+Wxg0MQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-25T16:28:44Z"
    mac: ENC[AES256_GCM,data:cOo86KgqV98jAYkmao7pATehnsgULP1+2K1v/+JmZctlorb901pHi4/MhymJbeXe3ZrJzFFQQ5nSTEX7LdLCFXoGJHqzDdh7aTpbdD/zpba/jBfN2RcyGZb0+/VAjfj4STQ9pWcIKVU7FKo/fqFjLnqWcphuU1pZ322K7CnarYw=,iv:S7GAF1Qi/7GnMp5kl7nta49fQgp0w3HFpgusZJtE7ss=,tag:cDI2Zsw2r84LwNIPSwrfVw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
