---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app media-browser
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: kah-common-chart
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    global:
      nameOverride: *app
    image:
      repository: filebrowser/filebrowser
      tag: v2.22.4
    env:
      FB_DATABASE: "/config/filebrowser.db"
      FB_ROOT: "/media"
      FB_LOG: "stdout"
      FB_NOAUTH: "true"
      TZ: "${TIMEZONE}"
    service:
      main:
        ports:
          http:
            port: &port 80
    probes:
      liveness: &probes
        enabled: true
        custom: true
        spec:
          httpGet:
            path: /health
            port: *port
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
      readiness: *probes
      startup:
        enabled: false
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          hajimari.io/enable: "true"
          hajimari.io/group: "media"
          hajimari.io/icon: "folder-multiple-images"
        hosts:
          - host: "media.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
          - host: "files.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "files.${SECRET_DOMAIN}"
              - "media.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: media-browser-config-v1
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "10.1.0.104"
            path: /Media
        mountPath: /media
        readOnly: true
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 750Mi
