---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config-v2
  namespace: media
  labels:
    kasten.io/backup-volume: "enabled"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: ceph-block
