---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: plex
      version: 6.2.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: node-feature-discovery
      namespace: kube-system
    - name: intel-gpu-plugin
      namespace: kube-system
  values:
    image:
      repository: ghcr.io/k8s-at-home/plex
      tag: v1.25.9.5721-965587f64
    env:
      TZ: "${TIMEZONE}"
      ADVERTISE_IP: https://plex.56kbps.io:443
      VERSION: docker
      PLEX_PREFERENCE_1: "FriendlyName=kubernetes"
    podSecurityContext:
      supplementalGroups:
        - 44
        - 109
        - 100
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: "${METALLB_PLEX_ADDR}"
        externalTrafficPolicy: Local
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          external-dns/cloudflare-proxied: "false"
          hajimari.io/enable: "false"
          hajimari.io/icon: "plex"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "plex.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "plex.${SECRET_DOMAIN}"
            secretName: plex-tls
    persistence:
      config:
        enabled: true
        existingClaim: plex-config-v1
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "10.1.0.254"
            path: /volume1/Media
        mountPath: /media
        readOnly: true
      backup:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "10.1.0.254"
            path: /volume1/Data/backups/plex
        mountPath: /config/Backups
        readOnly: false
      shield-profile:
        name: plex-profiles
        enabled: true
        type: configMap
        mountPath: "/usr/lib/plexmediaserver/Resources/Profiles/Android-SHEILD Android TV.xml"
        subPath: shield.xml
      transcode:
        enabled: true
        type: emptyDir
        medium: Memory
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: feature.node.kubernetes.io/custom-intel-gpu
                  operator: In
                  values:
                    - "true"
    podAnnotations:
      configmap.reloader.stakater.com/reload: "plex-promtail"
    resources:
      requests:
        gpu.intel.com/i915: 1
        cpu: 1000m
        memory: 1000Mi
      limits:
        gpu.intel.com/i915: 1
        memory: 16000Mi
