# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: radarr
    namespace: media
type: Opaque
data:
    RADARR_API_KEY: ENC[AES256_GCM,data:614jQlAr2npVP6U8FaD9qslSB4nyspvsDIee4sIRJQA=,iv:bnnFKlBLfeB0Q0cYksYwJ58j1jmVAuSHO8IidF6bLaE=,tag:lZzIZOQnjtvPt71jrq5dbg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age179qz74lpav0lcywkjzujhnlu3ukq9kgz9jdxm2u59w47j337kc2q0e8q20
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUTUZObEo5VHdrRjZsV0gy
            azFjeHJPeVBpTXhEUXU4ZmkxOElZc0tscmxzCjE1MGFIdm40QjMxS2p3ZHlWNEQy
            MWRvL2s1Q2VhV2xJRWlxKzhtZk9XOWcKLS0tIEU4UDl4aWJyZFhUZHM0Z2RVaUhw
            NnVVYUpLamZQREdidkJ5UG10YjZObGcKbNkmMwxmhTnMrgsLTzo6MYyKPDraKISX
            iFB7dfk9e5yFeN5y+GmN2+VQnm70BMpSI+z6CcAtgBP9HbRjkiQdOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-05T18:53:57Z"
    mac: ENC[AES256_GCM,data:V+zSLVNJmwaxkrbj9EfeyIZ3AWcWfnZxh78orSymsZCnfGnlE2NCCKHKX1UVshTd6PKRtjObON6B8OTos9dmVFYTRRHz/PbeIWhmHw67jDyKuGMtAT5CuDuyL1NJEwi0p8EB3aEKIg1ItLTsKL+jbvT3F5OspDzAHlFd4MaxOt8=,iv:NIV5H1dS/Y51N5zarKI1cAvAZ/mSQHYW1wsiuFL88G8=,tag:iZAi4K9nCFNGTobwQBygug==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
