---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app zwavejs2mqtt
  namespace: home
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: app-template
      version: 1.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: node-feature-discovery
      namespace: kube-system
  values:
    global:
      nameOverride: *app
    image:
      repository: ghcr.io/zwave-js/zwavejs2mqtt
      tag: 6.15.2
    env:
      TZ: "${TIMEZONE}"
    envFrom:
      - secretRef:
          name: *app
    service:
      main:
        ports:
          http:
            port: 8091
          websocket:
            enabled: true
            port: 3000
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "router-wireless"
          hajimari.io/group: "automation"
          external-dns/is-public: "true"
        hosts:
          - host: "zwave.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "zwave.${SECRET_DOMAIN}"
    securityContext:
      privileged: true
    persistence:
      config:
        enabled: true
        existingClaim: zwavejs2mqtt-config-v1
        mountPath: "/usr/src/app/store"
      usb:
        enabled: true
        type: hostPath
        hostPath: /dev/serial/by-id/usb-0658_0200-if00
        hostPathType: CharDevice
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: feature.node.kubernetes.io/custom-zwave
                  operator: In
                  values:
                    - "true"
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 500Mi
