# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ALERT_MANAGER_SLACK_WEBHOOK: ENC[AES256_GCM,data:IH2tFmsC5oCWXplUJZkBi/pLlAWUt1A21gQuYunoVeqDXrObgv6hyDyTREHz3bQjEuNGBa/6GTvKEkE8j9lFdnQqrKaD7OK3iZa1avjz5C/k,iv:lB9lniQUGVM9ELxLfUb8O0tyaRgPHzmAm2E0r/9yENc=,tag:eABl31zPRsVhC93Py2OQog==,type:str]
    SECRET_ALERT_MANAGER_DISCORD_WEBHOOK: ENC[AES256_GCM,data:DYCVkKefhpF68S+vcDRo24qMo9YR7Aj7UxqX2WY7bqy6M8fsZdpEg7CD7EycwVWVe/0akZLf/UfIAofgZhqzy8m4oTGzKGFl+wuhId0kibpb4b9D1pDyMw8pRKZ0g16yiW/sgG+oq1Mu2ZMhKGQZuEv4MbZ49DHE,iv:ZEq7YaXKL+BHBnjXafU3BWl1Pa98fOya8ATgAH4GjHs=,tag:nrc16u5YqkU/AgYkxomI6Q==,type:str]
    SECRET_AZURE_ACCOUNT_NAME: ENC[AES256_GCM,data:rHgvJ4nCS/dAo3c=,iv:7n3BWUk6D1BBt/r+5a6X7Wzi2Syp4xELJ+3D1LQ4dek=,tag:0QTmutPdfNBpVyUMWF5qoQ==,type:str]
    SECRET_AZURE_ACCOUNT_KEY: ENC[AES256_GCM,data:pB7nW6pHIaO+EhasTvHNHfElJi0pnvQt7xTILjv7xV38VZf8uq863ru+UfEh2aq/WUxeHlwzan4F+X/2IWUe/cW1JmW3OazxiaaLP0vVCePINwJylnmr8A==,iv:loCXmrshnBs4JGtMJerBwSLuaHG0veS58oa/imqkjvI=,tag:gcdGPAo2vJNx204BBf+rWg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:I+yO3frqbs1RsXTta/cB6FJqPy0u,iv:MwGZYW2rGDwXUfoLGF0ORrST5XEVk3q/4nF7mEYXJeY=,tag:fzM/7dQv9Ak5sxkmXLWOWg==,type:str]
    SECRET_GRAFANA_PASSWORD: ENC[AES256_GCM,data:+n55gqt7JqATm+d28/8=,iv:FJWEtQxdF/2x0Qh/DS4PHWmfcZvBDIaQ6t/Bn1PmqXY=,tag:8pR1Td2uwq56xALfxBv9vQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:H5MomzJN5O0K,iv:Ki6I32fVobooOMSAg7pq4Xr/PqlM9K3alzu/hsp/e34=,tag:o/xkSQc8S3+zUenwvUGQzA==,type:str]
    SECRET_PRIVATE_DOMAIN: ENC[AES256_GCM,data:uF4eK3+9DirjGTD5pI7v,iv:/JYSueNIgFBQBjEbivh1n4gqIDFU9LF2IbzTgFi+trA=,tag:kRTtdHyLG1FjMS0dTaA6og==,type:str]
    SECRET_MQTT_USERNAME: ENC[AES256_GCM,data:dP3OD90Vph9m,iv:lF0cW2hRBTYyNMhyhjq4heK/ym+a1ydnIBSZmlvoLss=,tag:nV6N1KkH3o0T1Ifql+4now==,type:str]
    SECRET_MQTT_PASSWORD: ENC[AES256_GCM,data:2kBWRgI0pjJ4k90s3Rk=,iv:ti4mw08ic8XDgrNiseLpmkpFPKgDKVb1Jv3YeuSOvUE=,tag:YES52GKh1Aw5unb0aiQxLA==,type:str]
    SECRET_NEXTDNS_ID: ENC[AES256_GCM,data:yvgvHWcN,iv:22knGJlfTdrz6kou8nb3DVOCqR34fu7NZgXMk2NgCPs=,tag:2pqoPfqrNZu2wwcgkzy94Q==,type:str]
    SECRET_RING_TOKEN: ENC[AES256_GCM,data:kVlDN4AmXnLJLFO7uBhNlYNT+QzsKGock5PVl67yXijGgf0cl9J+FRQNJKYVt0Og7sL8dyVH0ni4UO+fU2k9Wq7H3+T/iPr5jdVuKMR5vqSHeZ/ctiZpcBzU9NqknLELDrX5CwZYrV/V36Y5hKTTCU2e0YjGa11C9E8FljoG/Zbe6tyaYUqPyoeRhQqj/9KCK08x9UyWzU5647IGcmH8pTDo+GtlCm6QdaCxJH42Q22MkV3DZuaPyYxetVc/HMZFh/vFOBdhKbowSbdz24wutFuehDHK2Q3DNCSI7lCMrM1K0hqw7Fjl/MnF13uCY8R5PfxzZ+rthxvPPWmA0aWytvv2Qlr1g+9cer05Iq0y4o3A5ai2ztXsHHA5O1AbQsU6q0pcws9aySIrJ2Bzd/bWkufD5gn7qp0bTIxFUUnvzxP/aY1gJGaWpLxaKlPQILR7pwBxg2rcJvc2vKOI81ig+sQ5+yW2K5E48KRTKracIegt7Jab5IfCEgjnINKJtg3pUqFtt1zcc0kg8Y3Ch1W61XUb3JL1MLgpS7IRHr9DUa9026X+N2y0a/a7ySrbNxZFY2zwKu6C32PjITDRzaXgFPzyqfO/QUNNyNPw7FfTMmzldGLDQzxtC9bMm/955xPnDu7Cm135gfgENlIMJMTRK8mFG9z8axwZEDIdq7TK5yoCT8uy6oBhpqrX/K/cVTA5IQ==,iv:Ln9c2MR9pTNuAh3nFltNQuu7zntlE3sWThw+vWiJW/4=,tag:c17F+4Mf3K1a/JZyXv0RnQ==,type:str]
    SECRET_QB_USERNAME: ENC[AES256_GCM,data:E1PEoYVJiKFtj2IRuKIW75xmaqcT,iv:YUZ5GI8ETbdQnxj22/QSF9a5UvFdZDPyUoOflVC9JKQ=,tag:uKNylPzWN9jwMPAIh/K4Tg==,type:str]
    SECRET_QB_PASSWORD: ENC[AES256_GCM,data:ZvNWHAzfr8Oce+lVVlgDRgEc9wVq,iv:zMGVmyrIKW3x9isn8flT6wZrcgTEAx3hvCKPdHRJI8c=,tag:qzU3S+OGSPN5tXTSTiszvQ==,type:str]
    SECRET_AUTHENTIK_KEY: ENC[AES256_GCM,data:SYcoSyM1iRR228X8iC8BK07cYGyuM5CZxzkqQiXG7J77ha+BxyBNdimqxCqX8LeHamk=,iv:UfJbhyKJoBVKdaJR7UrUdyEjRSV7YYkZMElPFwjPpRg=,tag:c6TD7v8AnW6UtxQbP4t0Fg==,type:str]
    SECRET_AUTHENTIK_POSTGRES_PASS: ENC[AES256_GCM,data:KwkCvOfa3bpdUPa4DRSIhLF67zvZtL1D0Y1HF/ZpVX9c6i239Kd/B2GxcH2mC3fKHpE=,iv:m5gtIlWR2YC/q5Jcktr+KUnH/TqH1P592P8SIMy1rto=,tag:DFhqxfDNgl7djr/JfrLPJA==,type:str]
    SECRET_TESLAMATE_POSTGRES_PASS: ENC[AES256_GCM,data:spuwS0Y+2ZReg+l8qDEYPP79058oLGT17cE41vIRtunWSNr+jJVQtqCxkLtuDsKbdv8=,iv:V/Wmo4Cj7xYasnwlpiUVdjI6TRwrLdGT0UxFSnP4f1Y=,tag:l7jn3lUpYQgqMbwqAPpykQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age179qz74lpav0lcywkjzujhnlu3ukq9kgz9jdxm2u59w47j337kc2q0e8q20
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPMzlFWXNzaW5TS2hhNmd0
            YmQrK0hzMUtxYnY5WHhaU083eldtWXIveUNzCi9WdWloTkRZc3hWVzkxb1R2UUZm
            dUdWeFA5OFNrNkszcDVzbW5oaHZxbkkKLS0tIC9EM1J2OXVoL2JOSVlEb0JhL1Yr
            dG1FNU1CazByWFpsVFp4ZzhlM2M1RzAKssLa3zsBXaLMB3cgCDQUZOz8Qkldg4kP
            /gHZ3eE8LyckzkXWKMRQ1jSVhrNRs4wCis/pOQFG51jm22lM0cFWZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-16T16:36:00Z"
    mac: ENC[AES256_GCM,data:6m2ko+jElKJ6RVeypk9aWKntupAohBvz/Q5L9M06NVtIPK/eFipSoGOnip6s9GhYg9/XGAvevXlTh2/AiKirniz7MHt0iTz7Skhl55Qh7TbkvETSEOikhUz7YnfzWT6pdwcTeI0hSe9vNM9qQu0kZcw/Wggh12Vy5dNl9xxTNrE=,iv:ZUZbbyA3TDGirHUpCv4Dh8Gs+f570rYs/jWF1+XAS/w=,tag:A0TophmMVNcZ8trwWm8Uog==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
