# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:DxZb7UIr3Zs3,iv:FekI/x6Cc0nMW1DkUEaHkJvJ4PHqxuP4prtw6yem4wU=,tag:HRCC7SjmvI4Ha7ulMCpS+g==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:KDeOcMlBFCgCfOV7aV6ImoVBXGrq,iv:woOFvnVzjwjp9pHhnNu28PDIw+OsJtJY4MdQOpwocZg=,tag:t6Hix3mNNnLqXjPpYW8Pmw==,type:str]
    SECRET_MQTT_USERNAME: ENC[AES256_GCM,data:/zB6C1kIJQ1U,iv:l6JvKNKsM6z1GJ+yvWqpdLufN4kHGHgzGVqlMaBDc5Q=,tag:NBdJVioXKBwffH7JMoTyAw==,type:str]
    SECRET_MQTT_PASSWORD: ENC[AES256_GCM,data:hldTkhuU1+dE4Q4EU1E=,iv:lxmxs6ed1xkexwvZ67NetTnoPPJt610JsTtZtKb8SIo=,tag:6IMm9t5Hypt8bh8Nycdurw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age179qz74lpav0lcywkjzujhnlu3ukq9kgz9jdxm2u59w47j337kc2q0e8q20
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJSjhiRk1qNUI1MDJJWGJH
            VEx3YmFqb3FQRXY1M284Rjd6bGlwdThnSEFJCjMzVS8vVzZDN25BL0IvbTRvcGdo
            N1VFdExRSG5IM2dZS3RrK05GcHhyRUUKLS0tIGkwN0prdXIzUkJySHJ5cW85TmlN
            YTB2SlZIWkVFQzFUSGRqUXdQRjl1STQKhC13GIeO+sLC5jleQYLreh6BPfd5odBx
            +N4DGZ89UHv8dgL91TZSA/8MA/ELaJtAhUmK+6qkiuSwqzeJFaMQ8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-02T04:55:23Z"
    mac: ENC[AES256_GCM,data:+WZhKsiU7J7iRtny1mG/z6AedKGtIY7g7qcI36o5nR1haSbDNuV5VKIAZWOJuGM0S3I2XGNGNTE9DEG/k4syRXIStNMBB/lobBpw8+esY20W2AHva72oeW/dTH+iMMAzir3OeSYZA9JaWSIXbVB34Y3LC85z5Pud2fIT7KFgcFM=,iv:7UVaBeGywfq0J/uOjZP3XXHY3XT5iw+DL4CvO1B+aPY=,tag:AOTG9axDU6lbnY6D1dkQwQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
