# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ALERT_MANAGER_SLACK_WEBHOOK: ENC[AES256_GCM,data:iZrUgY4slik3sI6dsAFafpeq8v3frTwehihj/QQX/vnYYF9gy0WTGmMZUPou79HjIy2yccWCUUowpA2FzFTmVge0ft7YIGfsBdjFAH2UIy8t,iv:4Rp0ImoRURyY3Vxt6gYJPs9q7LIk0hl+gALx5S6sgww=,tag:lfWZCrKzKA3uWu7e6Vf9kQ==,type:str]
    SECRET_AZURE_ACCOUNT_NAME: ENC[AES256_GCM,data:2xawH4ifNA5/GWQ=,iv:ItYh1B0/kgkdZ1RBUJiwmxXior3pGBSwDvUOg5AUBp0=,tag:PTAsmXRiPf22Hi2BUnvpug==,type:str]
    SECRET_AZURE_ACCOUNT_KEY: ENC[AES256_GCM,data:05YDYJEG2bhDSj0P5JP/nbVJ4Ok3fCNOBpqWjiz1BhyZe8kf1kZ5LByY8y9JqJecphLd5KvUvPDDVBbuZ5okglFmvIZmW27MVmYPN24Xo0Bp1ww/4yElwQ==,iv:Wo+j5azN/ej1ScLfUqKhGSSioWKM9jXENAgiazVTxes=,tag:IwaiV/WNHJGWzDjLkky+/g==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:+5E00KE4TvTBu4M6QQDNbfRH/EoM,iv:JLVaKp4nUa9NlK1eKvaYqdVOsM1OGCoJWFJ5lKL150g=,tag:/rbQ9slGI7dRnHZlKNNInw==,type:str]
    SECRET_GRAFANA_PASSWORD: ENC[AES256_GCM,data:Ixxqv03vXS0Bn6YnXw4=,iv:8p+ZKF1R/bogH8/mr+SAiiwKs03zhX1WTpC/XHtlQLo=,tag:8wEtEsotqiGrVZc9/hwZ7g==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:OaY0WcaOplxr,iv:9l1RZt7eH0ihm9hXrxfA5JIeSX0fPcvxoijVjrCa0ao=,tag:Vyd1HheoTUq4rJKF832bzA==,type:str]
    SECRET_MQTT_USERNAME: ENC[AES256_GCM,data:t710tzZwmkE3,iv:JvKXP7X9gSINLzFkdyNWAeA7lWW4VyacuhdBlKXyX4I=,tag:OH8z1wqw5pTZgskKR2afpQ==,type:str]
    SECRET_MQTT_PASSWORD: ENC[AES256_GCM,data:Xidk0UFusJ/qx5NSHYw=,iv:wcVyk3bnRk1/ZBICQJrYhHQarWSXBFdq65XQjZgCJME=,tag:rF0zaKNbgVO29s+oAK2nYQ==,type:str]
    SECRET_NEXTDNS_ID: ENC[AES256_GCM,data:x8XGF6jZ,iv:FRKR1DFKMX47zIV0Rp0y2kuJJM1Sm/taKkBjcq34z/Q=,tag:wJxqxJegmxUuFNeiu+ofOw==,type:str]
    SECRET_RING_TOKEN: ENC[AES256_GCM,data:GryGuHF8CuLjf7Ju7Rza23/nO3oOwg9G44b+lmUd7V0VGaOK0hcjNDFdvEfRCdfZc755V83s0i2E4POkquyl5v+IO2BuRDaqqLBbVMQEmNKbFOt8WQmoTRWZOEEipUyGdxGqWXxsEcKwX0LwrwQzrAvQoIBAcGPTBuaAuitMKSf8Xq73l+MlGSUNmI0mbH72KyYfKCVCegp3A8dlO4p8tv1TjfGD+2L1hdV9/OH1kKrKm9XjmMo0ossTw9nK7948UHYdKyjeePpTGhCrSzF+mPpKXJ03P32OSLDBy8w/Ez/zirhjSHFbmLFbaQvCdCjGjCbRqzGMzBiLCid5tJMHr9gCcLS8dK05qH2hbI2fo6PNuQccD3zK2D0HUY56SAH1KRkUvF5X7V3vD+ut4QSW4P8B0lEhlVIP484x41p61wHx97jtr0oU24gPAS2Ot5PG7sh8U0jOi70Tyq87i1OO3Gq3UmJvpOi0oqW1PQ+4lly428BNzaoylBy+oPkADR8Qy9SzDq+pUln+gp/ebW3jQFSwY8sjU9s/OzatAVxg0YosuAy7xAZCYsqAxFVEJ86OBR+esq/K/JzJUCOErScZgJhDfH+6LAX/0LGFiEeu7mBHk8J0z66g3nB+o0f343w0tNcE2Kfen5TIIXSsMiIC9cIYjeue+9IVqCMJp3GQriX7X2N+/Wr/7AFBFbViVPytMA==,iv:2SHlbAgiVmvVR2HiRsAIb6agTHygzEQUWstucPyvcxc=,tag:wjqVCbhoXypDnluNaQ9L1w==,type:str]
    SECRET_QB_USERNAME: ENC[AES256_GCM,data:YIJfhV8yTFhNvLq+eUE0IIkiMsYQ,iv:Nec24Sm5yVw32q7TWz2nX0C/gcxELyxPlOkUdVUa9pA=,tag:7ThTknhYthS/cJhrG2zFBg==,type:str]
    SECRET_QB_PASSWORD: ENC[AES256_GCM,data:U8yFFImt6QAgPwyf0ppzO887a71h,iv:nO30b36EQS81MRzvomAJaaND8epI0NaXO/ArCy9xiJY=,tag:Cz0odsMVsTgJM/F33nbUkw==,type:str]
    SECRET_AUTHENTIK_KEY: ENC[AES256_GCM,data:zaYxbdI/uDAA24Z9VvvVaN+tiuMQ1IQQw1gepOQeZ9PdVOjSyxxZZaNfHixyKkleS/o=,iv:9fYptSFjQp1ypPqWk76CLiRqthQQLBz0jIdupJj4WXo=,tag:ynnYiJafjGi63bUxUmHOpw==,type:str]
    SECRET_AUTHENTIK_POSTGRES_PASS: ENC[AES256_GCM,data:T28dPSX87P+J7A9Z0tO+u+FUqRwOxRzaZNmCWinSaZt9Ipa0a9twbKbWFZb2EG18X8c=,iv:WCb8jx8JC+30aIhpBN/LNy5O4EIYqFKCoegZ3pZQGk8=,tag:el9syDaZDefQv9cc8zewRg==,type:str]
    SECRET_TESLAMATE_POSTGRES_PASS: ENC[AES256_GCM,data:d0qJreWxgUq+JMqkIQ332K4Gi/RQ5VQtscw9zZBg8uwA/+b6xpOMM2YLN9wHiA2afsc=,iv:srifCImlw5khwgwA6+86ajXF+mOAgwH9DdDYABxw2tU=,tag:oe3cGYR7uTcbD7k+qIwSRg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age179qz74lpav0lcywkjzujhnlu3ukq9kgz9jdxm2u59w47j337kc2q0e8q20
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIRkkyUDcwMkRLcThMbjNV
            SWZ5NllUWmM5OFRmT0U0akdyUVhKM0RmNWlnCmNXZnN4Mk5ZcnlJby8zemxIcHNw
            Nmx2Lzc0Rm5zMVA4RDZ3QlFmekF2cTAKLS0tIE5zSGlYK1crVkFwdmRrYXYxMGZn
            S0F4TUJrc2FOM1NMZ01tbitzc3pKTnMKIbipeR3H+8JHGrTmyin0jWId9PAj+hm2
            /ZUg9bvP2qoTO3/2XmRJJgAMpHZqpUoZbwrNAJzCmEZDBL/FClKYpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-10T05:02:24Z"
    mac: ENC[AES256_GCM,data:5RPrPTyUPJhcCQs5KCB5xFef7fbXmXyunvgDLHzmKoWxfdnOkNrN6UC10RRKeg+lpVfEr7tHzV2GrwZAGMogzeVbBX/NvuP7CE8XRHQst7JulA9c68Ck/r0Zl2QYWyVZhWtd7Sb7RybdI5qYz62JERC3GVSXd1kXma7KjIX6nlk=,iv:ywtqkk6m8fPqD111k0eKsLNNT1ETEMstZv1Ub6VpA6E=,tag:qSiPdzoju9XxSH6RVCTZFQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
