# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ALERT_MANAGER_SLACK_WEBHOOK: ENC[AES256_GCM,data:46mN+P1DYWH+jrmaHdb0taoY5UDcJQUNwwKtN8aki3091KtR+qpjGBrsRt51ckWK05h3lPI7jnn36nkkXwoC6FmjY97eVp0CL0f6Grr0CHYX,iv:9LF1ZHGIFtAXdPYbfyLHkm5TjjjsctzmfV7EeutDA3w=,tag:Gy05G/chLJidM20o5kXg0g==,type:str]
    SECRET_AZURE_ACCOUNT_NAME: ENC[AES256_GCM,data:2mjNzAvCHJhzAVk=,iv:nQNp+xrXmYKSXT19a1pvNQTqV1zk7x0GFxWX9f/B318=,tag:hh4msBZfAhE+I0AUQZ2XdA==,type:str]
    SECRET_AZURE_ACCOUNT_KEY: ENC[AES256_GCM,data:Oh5SPtGLI7N/j1/jwU81+Wltx98+CSP7oT0mJbAb7RhDAxZeQT96ruiMBmvbMQ1BQPoIdRdlqoYGdUnzFmssze8JmaD4Q2Q0IypdO9CNVpo6mJBNIimkdQ==,iv:2pX8txDIsHnWzX+aCLOJXKsoEyTB6Fhav8cY/Ji3PbE=,tag:jZlhGZMHjEot5rwFePVefA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:lve6Fo66enQSWGffAXpTz13H1idn,iv:2WZdVo0ETQnzmAvY67OxPqYjdEDNhoB+rgFADiqPJNo=,tag:3/gLpu4zmZOlJwwQ61uBng==,type:str]
    SECRET_GRAFANA_PASSWORD: ENC[AES256_GCM,data:tSJ2pMr0F6FgEVzQW6g=,iv:2Sj1Ybwh+/zBSrfxytcpF6+QNYeW0vVN65bRlhj1X6U=,tag:aJb2zcgJI+rO/gea98yB1Q==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:jbAdVDkd4s3u,iv:TomFyvZQkp+xYKD/G0JhtUx9mZfiRvJOGvx5rIjLRko=,tag:yQvVBv3N3cH7yviFn3BnIA==,type:str]
    SECRET_MQTT_USERNAME: ENC[AES256_GCM,data:d4lygOsyP1KH,iv:W1+clhHt2PkIIIAcT0FgD2eiA87NiJGRPBAYIbBCi8g=,tag:ta1xghZmfX9tOG+nfI113w==,type:str]
    SECRET_MQTT_PASSWORD: ENC[AES256_GCM,data:qD/VICcyuT0+BWr0RFY=,iv:JqDG6MYYaFXBM0o00tT8MYaEcmADHQYxFTsngTPh7j8=,tag:m+sa9kZe1+Q+Sbos3Uo6iA==,type:str]
    SECRET_RING_TOKEN: ENC[AES256_GCM,data:HTZ+7KJEafMthBosT/KeeHGh3nUHjKAcgbT6Z6ev02XVAz3/TyjqtXd0pg8oMdo1BUKFPHymwDI1Sfd7zj36niq0epnexeuHYpXUk2phB28MtxUA7ko8EgI8BXb7K1DE03SQZZ04jxXNCCaTr8PIwFBiHCdfke2IkPGqs9zfqG6JTU3Xbb9bd7P7otPMBdBa6+7MQs6hXVbtZGfdqEb7ePX/W66npiCLEEJCIyObVYRdAbcoYnWtr7DiTvZpo2xpezMTQsWkuK7PhvTo1KQLDVJxuao+W2afRNcKlLH7j6J2cN5+hS/+KcM+DTaSPOSk640DK0tIPGhDcZxAcB2oqsnOWRCbGq1wiGEUUGN6jR/Ghfqw62N4x0n6bdKfWvlP81rFcou266BTVgT64zWrxz1T9ntyjyaG7Bl0ltszQ6q4LVq3Acv5QZj8azJvm8ip2QiVBTKqX6Sr8koxAxJP4CjyaM1Y2LTqAgh+sZjRaN3mi5fLXZGU4PKVh11YSi84HsTfH3MKfCX2ZMAD8GyNoyUmOa0Cpn44ATRwS7RjinBRI5DJ/5OXGomfh38OKlVvOjr4Ld9KIQwtKS7cBk838JpfesqD8d759yIIaGsVfZagzQizYhOrMiPFG6J1uAQJGQI1nPgYhydt/0F+VcTJvN6AW7Q5HkTGhBa2Ral6At4e6/fh6FLr/ZBRz3g+ssxqBw==,iv:mvYLK4MvZDV7fXBGLMtEN8SHER0Hlx9YD5EZEUTOovg=,tag:WY1n2M5i92XHIzkagyazvQ==,type:str]
    SECRET_QB_USERNAME: ENC[AES256_GCM,data:9qrF1auxJTMCFIwxe3EgKFum8QwX,iv:23IUYPOIP3xxWdwUZndNKpwrnmhiCO09GC06TwWuSrA=,tag:ZCuohAIg/NPSNvCdiqVlUA==,type:str]
    SECRET_QB_PASSWORD: ENC[AES256_GCM,data:gkBGDduotWeWkHMVmh2rWqv0p/uE,iv:54fYMGLf0/n0KuVN7ZjvDb0HRQEjgkIDLQX7OmzOiCo=,tag:whQonms8/r0b6WbAeTNb9A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age179qz74lpav0lcywkjzujhnlu3ukq9kgz9jdxm2u59w47j337kc2q0e8q20
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWSWJVc3BNTExiYjNxakta
            QlhpWjFZWXdYOTJ1TDZpTFgzZE1WSy9XSUYwCktLbCtSZmh6Z3lZZzE3UEFjcnk5
            UzlzbG11dFlKTGxVV05EeHNNMUNKU2MKLS0tIHFDZUtBZnFFai9yYTBNWkVmMTNR
            M040bGN3elBENWxlV2dHWHBLemk4TFUKY7iqbm0YFonSIGPFfsbaf6ZZNPq44jz7
            fGzbJ99UVv/VWn8ehkn8K7SCw0tDzfZV1kr7wfxtCMT3hvbKACulEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-07T04:41:49Z"
    mac: ENC[AES256_GCM,data:4un2ARUbt0q15vzyJDDkWrZYGMuoMw/3PtHBb6Udl4c9hhizuKi0iT4Ago2/kc7prxOVFfMkK1jVhv/zCJcRLWx1PvJinjm6KkAaVpiX61vknP/NnT/6PvETWklIwIsREoQCRlnT7BBYyomTVkdSHchmoCTQcKyZzfy+Hab64Bc=,iv:5QS2MloMduZeuzmiPcDXFbX1TEyDWqixQKGHLW71Css=,tag:J4+3jZIzHZG8hw1dpEdMvg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
