# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:5YlV69ZHZmA7,iv:+sbNhC71PauOft/n6LwgRvh9NKdUijizLA4OOJG0SYw=,tag:gT5Lasn3jehWh1BVGUCZBw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:5k4M/WbKok0kA3YjGth/1E2pJXeP,iv:AmZ29qHda6i2RioGiC2z0Plc4ndrqesNNPm3IQPfOY0=,tag:kJfOOSQEu17mVZaPtV2cTQ==,type:str]
    SECRET_MQTT_USERNAME: ENC[AES256_GCM,data:z/IYuM9PWxj7,iv:0OqTl9r4aotxoRj0bXLCrmjC0K3xZcG9nO3JEbtj0RI=,tag:niTgvfH1VE7t3eZ7uKPeLQ==,type:str]
    SECRET_MQTT_PASSWORD: ENC[AES256_GCM,data:kAExUEdOJPdC4R/91wo=,iv:s5EAylgDBsIyoLCViGEQQPqM2OrcsuU7NQ3t6HTBmNI=,tag:tv2m5tb5ASZt7wTkWgY7ng==,type:str]
    SECRET_GRAFANA_PASSWORD: ENC[AES256_GCM,data:4iPRuNTFfEYBcUdmI64=,iv:ei9adcv7NB8z+SXHa2FUr65RVZ6O0eDHOE39WpcdWmM=,tag:eSwagkchhoNqCv+tuickWQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age179qz74lpav0lcywkjzujhnlu3ukq9kgz9jdxm2u59w47j337kc2q0e8q20
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByN0x6RDN5a095ZWlBR1Mx
            T0VFNFFJdFM0NG5DV2k0L1ZWZ3A2bzNlZ0dRCm9GL3VSZUVrOUY3Vy90SklsVTZT
            ajd4ODI0UUx1d010VVBIamFtUUVYSFEKLS0tIDhieDVTYzBVbml4cjRzUjJLSWNH
            dmZ4SHRrQUd1QjlXNkh3dUplZGFGdUUKwgET42/huUGa1h3yAW9StshBXN3DhTXP
            YW2gQQ3xO4FsHbOTilYtx/oiKqkl4G+lJpM3OVONvzWrthxbSfamOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-03T07:12:15Z"
    mac: ENC[AES256_GCM,data:Un9E9sH0iptuz2ttkkEy9HjEQbblsVQOOYW18ONSlHZrg6WT8sSjR9DeZ/mHmSd/VLsn1KfR6qFvYngY+wVQja+V7Yxb+zOyO3J8FZlhnpfIRlKazsT/ws3dSLi9zfbWiKsHrUvIedRLgP/MwwKSlInbiEZo4s5s5ydIaGFCLN8=,iv:CAArQ2dRAcRg+9hSTjOGj5K/8cNUmLv5vtVnY0NEe6s=,tag:UDVd9pntzrigmmOQOoSW3g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
