# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ALERT_MANAGER_SLACK_WEBHOOK: ENC[AES256_GCM,data:fHV+QYdvdtsh4howm2vdZfE+6szmxrAi0P23DIFYAFhjwpk7pJZl5GInDoBDHFmTZuPqTiHPBCnJUxruX3/XZ2Ry8+Crh3QjkuDNNA6vtFiN,iv:5L1qj7Fa1t0Od0Ay9Xo6SB8/w0qEJHaB9S6YgbMslXw=,tag:XfGlNZMns6vLSC1wTy7Kuw==,type:str]
    SECRET_AZURE_ACCOUNT_NAME: ENC[AES256_GCM,data:WBJUloU+7RKWzCQ=,iv:RM460SNROWTQCDKqgzeHE4gwTy4LOK43fLcupHUaf94=,tag:Pi4HwR3M4D/yqkPE3P7vdg==,type:str]
    SECRET_AZURE_ACCOUNT_KEY: ENC[AES256_GCM,data:wH+vjiRcgVsVXr4Jmfi87TJWHCqbN0k+jWzJrgNbnJ6TXjhYKxvwtcx8gM41CF5wl7cQAXyq3X1DwJHkHCT4oxw7Xun7mLFZ+CvpKwIeYZ7agdX0iXh9+A==,iv:q4ZOkHOmYsvQmMqpD3IywEvRgorWwai6HpRg8H5CPgw=,tag:68HvxM9wVeO+bO6mt7q0Zw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:kUS11srJKhCuU4HBOq7MZLNHBcFV,iv:YRfqTHvBV1MU9n8Bh2beywVq+L8+PZkZi6Nnfa9lt7Q=,tag:N0AbjT7oOPbHqGbve2HWLw==,type:str]
    SECRET_GRAFANA_PASSWORD: ENC[AES256_GCM,data:5kbyjwajY+hMfPGu3aw=,iv:FXaRgDnCcaPlLiG++PloXKmnKeuN1GXY1YXaDo/c7LI=,tag:cELMYIQl3VZB1Yfjqn5uVA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:+7KU5u0K3wtf,iv:s1P3JsFOgPTZYLfdQsxF9uAjRrbJ0HL7P3Dspfne8tw=,tag:nbd5vKQj77thMq3BohU1PQ==,type:str]
    SECRET_MQTT_USERNAME: ENC[AES256_GCM,data:DyB9u0bkOQ7g,iv:nt67tsYUUDWzPklV6evyHrvswPw+fGHVPjfm9wpVgAI=,tag:TBKrgrvr48x/BQ0vyUJPwg==,type:str]
    SECRET_MQTT_PASSWORD: ENC[AES256_GCM,data:r0+Z9PnERDKD3KcKEKc=,iv:sfO1zCBHxsnTMQgVGVYS561b9lzIZ/2EIQ+5QGPMTQE=,tag:eaFNE096Ssb0JEi9GoKc0Q==,type:str]
    SECRET_NEXTDNS_ID: ENC[AES256_GCM,data:+/rYbfE4,iv:iXLw3UIgYwjxBE4HlBHvRJL8sKyXo/9FFAGYSMwsTS4=,tag:yk1FMqAt6mYe08kcJciGQA==,type:str]
    SECRET_RING_TOKEN: ENC[AES256_GCM,data:WhZLYK/U50eXbY6qqo5/UAkBesFVhj4dqX7siAwNKujK0cA48R5c/gjNQlVPsV9J7wIRVd2YzoneCcm/0BV6+lDjinON+b1TjR7ZQC4Zvrn5ObJCtepv/9f9rHBmwVTtgoSjeug5QYJxfR3xYHQt41Iklz3cVYVzlEOYA/mfMQVjHUqaeBZR0QHL7nNQuOBSNyavQXGD3AR8OppRqAXX7caQKG8V3FaLID8ZY+HUCtaGzaMqYvAoIu8l/9LbNcsTmqqre7VM35T4PfnyMXG70EFJ9wWs6pjb5xsCoN1KQLdT2mpM5RT8bce8Y6SMbMxyRwTYQb+sejtr+QeIjBF0vxLc6UIPQzUsR06uYErFEjo/SSv1QO9mdS04OEmYodMzU6Im5vzIPaQdIR1FDIv6lUp8zcmDP6UHJWzAtGLn3kY/vv/n8ifxvVY7Abo397kXOR16ds4zzGROkM156ppgY/yJxSkhsfGJjzaK9ofZ8JtMxiMvAgePChOuHwcJPHmNtPy3CnQIJAijrMiBzEw/JHnQB53Wfojk94p5Y+rO9reHRDVy9XhSWLELRLgsaM1LYuAMcufGs7/TOt8H4hMjUqJYccmv8O3AbTO7x9dgXoFebhxk7k++STHgZUT0x5ySqOjkrtS1L4b1OzqZslmGUYEHm4eW729mKIDQd5oo5zdJiTRrd8ehLi0t7mlxY86ASg==,iv:/IoTYYlJLusr0i+9cf+HQ3EsqEzdwwTDBdv6PtSrgeI=,tag:RzpG+RZNKYncqrlZfRbFMA==,type:str]
    SECRET_QB_USERNAME: ENC[AES256_GCM,data:Ihl32gv+WXRVp9zDzr8OSwbWVui8,iv:ko8oYTDtRLJR49kkhne2TOtKsZfzUqMHk8y2MzwAZRI=,tag:+OFEINn8Oi0OqOxRaWD8VQ==,type:str]
    SECRET_QB_PASSWORD: ENC[AES256_GCM,data:jt54FWJ4vF7d9qK0bZOG+BscAnhn,iv:04j5LXOXgHo2q5VgLUO6EDsw3ZsBLJU9ui3H+IENSkQ=,tag:8odBKnP2/ZnSfbmF1EO7dg==,type:str]
    SECRET_AUTHENTIK_KEY: ENC[AES256_GCM,data:fvjZ8l+t+6rrQdLr8m0//8RrasuJnvHbijMzvkaGN7ohQ6LpgU0bKzLPdinK/KwCYnk=,iv:ObDOvB4gMVYKN88Z/xWsNxxl76thFxdXOFFX6FazbKc=,tag:jU0oDazQBKRDUYnOwgO6lg==,type:str]
    SECRET_AUTHENTIK_POSTGRES_PASS: ENC[AES256_GCM,data:UrrooxR3ZCRXLS2wjKUdO5ujQ/pX3Lsv7bUOjD4sbiWjkA9Adc15iJ7UUQqeutJHoSk=,iv:hiB1qWorVR5EDu1/37beV6/lFDOb3ABZKQ1wFQP79cQ=,tag:iP6AeVYt5MBVQ1CM3Lqlrw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age179qz74lpav0lcywkjzujhnlu3ukq9kgz9jdxm2u59w47j337kc2q0e8q20
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmOXBpT3M0U082eTFMVGtD
            bWQrSjFkcG9wZGIxaVlyaWhOZVB2TThGbFFFCmhhSG5WWWQwSXJ6aWtaMSt5WVk4
            N2NrczZEaTV1RS9BYUNxYWN4U2hWVmsKLS0tIGJ3S20vMU1uZDk0bUNpSDVqQzZp
            NmdFemN4NjdWaVVxdXMvM2pMcE1JK2cKzoYm6jKPKT+C3LKGJHuYwtQmtF5MIJsy
            cQ+Qyyx1D2tAbjwLLTvxHnMNJaYLUrQzKqa2T3dl/KVC32Iy2iV6tw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-10T04:44:26Z"
    mac: ENC[AES256_GCM,data:qg0kuTljskQ+vZeh3X8U+wlTDJwlLaESghO2J9MWFLSvP6rjZJH8ykvOM/1KnCdTT6cBBme2wBGvwLrisUMO2fvS5XNhhwG4UwkCC41fTezgEI5Mswku/4LgcnDjej3dA2O3ismLjPopukFpdhMv6HW3HGPZLxh7yI+yxGdViLU=,iv:401AjJaJxc0eVTDRbQcUTpvs+Vlh2X4Hk4k4L09/ZTo=,tag:mJJrTLKSIE+7otkF3XLwHw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
