# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ALERT_MANAGER_SLACK_WEBHOOK: ENC[AES256_GCM,data:7OeBH1t2ryxG+ULa+WxzOA+qQSWKXJxoSLX5qqKOZlGoplXEC+Dm9Whl/fXn04KarmXkxSjFvXm4LGyQ2PnsUGf1OCK8pnMM1C5BDIrP4S90,iv:LL2HqU/yjZTK7OUugLFBvSCbk0rG99wcwHPVXEye4Y4=,tag:j+dnjliL5JSo2JR4bkGFWg==,type:str]
    SECRET_ALERT_MANAGER_DISCORD_WEBHOOK: ENC[AES256_GCM,data:D0ze5I4vxyp+2BvRbr6NMsbWXx29NUMvAXcrlt7UDJieS+r/nzIGnaYp8KcesUHjLsggp0CCqbwgwhdElwMcp//IDbL7RlYusSQav89DwHYLzRNZP4H5v1TiucFedatl1h1SzUPR18/sEQEU+AZVJRGQUV3sgpRn,iv:/UHHsQum1v1Cd700DH/3hZUewmCz7FrpaniDNyJxjuo=,tag:Ul5TRIot+LxFRdzm1WDrPw==,type:str]
    SECRET_AZURE_ACCOUNT_NAME: ENC[AES256_GCM,data:FgtzktCqFJTg1U4=,iv:ZW8I9NSfnFnMp/tvu/tsSPmyi5b7miUYH4byGxEZ0J0=,tag:9RIBHzZe2tSwzNhQwKmLWA==,type:str]
    SECRET_AZURE_ACCOUNT_KEY: ENC[AES256_GCM,data:Apror0qprLvJfHyaLcwbaKdm1iD2bzG4xksX4rk/tBcVODbi4QV+bpg04tlh0hwtbILJGKZr89NNj9davAmSNnAMOA3n7ZFG8b7E7W6lomuroy/xxhp60A==,iv:+fcz14VXrNRGne+5Ifp4ecU8/lCLYE/RD9fJSX4w6qw=,tag:rnKOtrELfJXbH9T20K58ag==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:nenHaykNv2kZOUbbebiYbBEEnpwN,iv:lfQq9qmKTbd8M4pliXWTR0OTJsMpHzkNug4dsXK7Yeg=,tag:sDgPKOvpC0ADDqVmeQzzvg==,type:str]
    SECRET_GRAFANA_PASSWORD: ENC[AES256_GCM,data:Lf/kvk8hS46IHOkdgHI=,iv:kbBueCLODMOkdGs7fVYXp3dhPPVHBFd2WHbSPiocEw0=,tag:X3cDBbBFoDcjmXtpXFAwPA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:7xhBDhCNAZ0Y,iv:j1y7/eSn2RIov76e+qlsGEcj/ZfX6T2C2qaPbx7zj+Y=,tag:WNNpaVJ2LZPnteqjskqang==,type:str]
    SECRET_MQTT_USERNAME: ENC[AES256_GCM,data:+hvJaWJwggby,iv:Lzv9LbrtDE/p1LSD1ezQ2byBzkU0u8s9tjfHXSyp9TQ=,tag:i+XjQ2jcDAjmqjovuhZKag==,type:str]
    SECRET_MQTT_PASSWORD: ENC[AES256_GCM,data:+PewDszy0BkKbAOXbY0=,iv:hkQlxPtEV7CHEbk6UyEXiRfUuWn+PIjcEqgEyaUCyKk=,tag:OmDEQ1d7k82/qCgZLuFwqA==,type:str]
    SECRET_NEXTDNS_ID: ENC[AES256_GCM,data:V4lEer33,iv:KWi6c2BE+qPEN2zdD+ghfCChM3MPiy5I7eLD5MJInL0=,tag:GMFe1Bx3dJVkPbgBpAMC/A==,type:str]
    SECRET_RING_TOKEN: ENC[AES256_GCM,data:wI73X5lGHwhjDhbiFITRHl+bJ2/wE7xI6q0lSBbH43jt3RC3hBlMKxdRutUgVOAP4Fy7YrjYAApTczzC7dEWNrrRBh3NVc/Ze8hhZO1Gfi5gXwRcZhApDGzGUMJnCFCgYlwNQaGQ/MGWJ0p90IcZ8LSBpIVa+zY9SGqo8rdU9DbiMgUDPqX+howaGVNJahdBqt8UV4RTQSKJsIrRkyeg7hjbPX8YrkHRtMJLG5TIN5NzhveMHAOIp2ngZSFv3cP2phY4Ur8NbgVQ5Gwz7filoAyg1q0DoRhJn58WRVGmWWSlNE+Lgshx0k1wgt8AQVYWaUrns//YQSvq2yOTsmz5bhu3a96b4vwjBDBtuagxH6WiwTc9Nt+VCk8AKBBdoC/5zkwHypBZ+DUufJaHReAJf3/q5S/DvHm3MzfMgDhXebzOF1nohOGUfVUiQVS7o4fBGU6EcAyzfZFiigkLu8hwXTC5ha7ExSjcUpNBnjlSteD/iJ7qt7XkqNQCre9NMlo/fGTthmpKKruEW2g3sANjVXfzagdyIzjAvgDHkCuCQ7TE22osyt5kZbyLQULfCLI2sbb7uGCg1oG3V8zCAOHVhyItQLKmoVBdQhMkUhCQQ4zau+chqr/qx1N5MFIMzInUZDziHgrQBLjFroil1zNcTRAyi8zXnp1gasBEN+f5q1oZCQhxSWql37/BviZuUv8RKw==,iv:TfRjIaU0lvBa7kpg64iT1qy1ixl2dGWYM4UOmx9e0C0=,tag:2J9TmJrKvJPRbd/euU5tCQ==,type:str]
    SECRET_QB_USERNAME: ENC[AES256_GCM,data:v7d4T3vpaDttQVQGydrPaqI94eOr,iv:EjhychJHnRpekc2BtK+ognRkOVPko0XzDBz+Zih6+3E=,tag:bd2FrjdBhow+kFmBcWU5VQ==,type:str]
    SECRET_QB_PASSWORD: ENC[AES256_GCM,data:j9JMqSXUOgunwIp05BJV3RBO7Aou,iv:0RWCQMDU0Pid7S5aS78xVsPuCLFqDJLLTlkcG7t2oaA=,tag:GV8I/Ht2GPNBdlvvFcKbww==,type:str]
    SECRET_AUTHENTIK_KEY: ENC[AES256_GCM,data:KhHVO21nPj6nTXHdyKNnKY653dUNU3MkfQrAqmb55NjOXEUOvJL17gIeekX7CSMNtvM=,iv:WbPdMrA8z97tM7or6ZGJet314Xlrvu8PWkLpaJ5iyPc=,tag:oL1XNTV/l3TGmdHhJlGipA==,type:str]
    SECRET_AUTHENTIK_POSTGRES_PASS: ENC[AES256_GCM,data:dOUYVYM+fOV0BkRS/O79kgG4nUymx5KeGlyhrW8IKj0BGEggxqOZiVXdAJKbMEYdb8w=,iv:ngGsgRLgp+cbjyz9z8CKmjWAQBBeEEwiFQE+8GRPnZA=,tag:zi9AJRvRv2AgAlgGX6sV0A==,type:str]
    SECRET_TESLAMATE_POSTGRES_PASS: ENC[AES256_GCM,data:27DXCGviQ1hfHB8s/8pr2dGCvMgKAxvAbfhCdnP/42cvL3AEOm7g4lSt7+0HK2JaH6o=,iv:PB0N9u+snpIxsUREBf3Hv1ngNUxWQpVTuEmpFHeXB1I=,tag:0smKm61CXRO4vA4UPVVQrw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age179qz74lpav0lcywkjzujhnlu3ukq9kgz9jdxm2u59w47j337kc2q0e8q20
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrTW4yQXpOTU1wM0JiWDg4
            Q3dlaDd5M1V5YXMyemJvamZJYXB2dmVpcFhrCjVxZGJ3Ylh1enoxcHI2RzNESG9Y
            bDhoUU5JZ05KbFAzcGk4N2xGT1h5eUkKLS0tIHh2dElBTzdZUnNkNHN4aWxwOWlV
            YllIRjdLdG1QODZYV3VnbHkxTWlzbHcKVUdQMvVLsBOQNWdLEf8T1yeI6JNDF99l
            kAvy/f4Yo3Pr993oRq9XnSH6pLJXg5tyVWs9CufJ8+eXrpAaArhxjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-14T17:43:29Z"
    mac: ENC[AES256_GCM,data:EC9SsshMXKqrYlqqoxWUP7vL3mZQzFc2jwSgtvKg6K2azq7KAGTlriPx5/kgs9OVfT6NqV7Q3XgnFA3DGhidCIQ3ewFE1fGSqUFcYG5IGoJPc7ST1NIjo8M+LRW+1xssLDjjAhgCxdMxmmX04zlUVu6hymjJdftjSRMzso0rkgI=,iv:7WaYllBXZRcuecTKhMChf+V0FS/GKDseoNv6a2frqk8=,tag:ZsRQtJlN3RwuCBUSDdc+3A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
