# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ALERT_MANAGER_SLACK_WEBHOOK: ENC[AES256_GCM,data:AXY2lC0uRoU+iAKCGjELdbtEsVceQerRdjid6rN8r83FLZmS9fjsbvtJQotBTqfCGy64pi8DS9NANxDbZBxqnu1+uNPOQ+DAzJPbE4cL3syj,iv:FzE6HgJohgkLENUaQ/x7yKbi/sob39m2QzyI0TmHfQw=,tag:JMpUPMYgwCaDNNR++/u6Vw==,type:str]
    SECRET_AZURE_ACCOUNT_NAME: ENC[AES256_GCM,data:oYcaToKQsqa4vbw=,iv:Kfv+Js+6I/jxjR5ZhxRWtiwHzakmcZi5FLIa4ILHutw=,tag:C/JAKv0EG9uGDUHG1fIIfw==,type:str]
    SECRET_AZURE_ACCOUNT_KEY: ENC[AES256_GCM,data:xIcL5/2YmeErMLmZO+xzxat5jW2GwXs+MTGrTvg/kc7EVxsF8SJItWR3liX7iEACbRyn5+BOZEJaz8VVYu0pKO/fEvy0pzZD3V62C2GZXj5ogugWo8ZULQ==,iv:VHbxKObUNKNN0NQt5hVXIJK1YQTCsoxTuB050sgDNCU=,tag:Af1hebD11iXPhypca+VJUw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:/1NHtB83b12lGLaVNqM7b0dlRFDE,iv:+Zlw0cXmRK/oik7fT2XL7RKi2EN20GPUKH0qxQ5XX7E=,tag:oP5bxOJEpo0ho5YV+h2LKQ==,type:str]
    SECRET_GRAFANA_PASSWORD: ENC[AES256_GCM,data:gXlI0f2l+q/m6E4oDaI=,iv:8qLfDLnwHeOERlqs++qjErL/Wf14DDj+evENSetwrLg=,tag:smPTAdTZmRZMa79gmEgCxA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:S37xg0EjR1UB,iv:szCkq+C+PBBQsTIdrkyCuSuVIWQAyGkIZX4bIfQ+ncM=,tag:92eotyykYFcgGGxK0LJXAQ==,type:str]
    SECRET_MQTT_USERNAME: ENC[AES256_GCM,data:fomF6uNtmk6U,iv:iSe+3uxUBbkE5EiZJPsvEpEfvR3VWoRe8jZPdPan9ng=,tag:oMdVsklKgcE5m9Cq87UYOg==,type:str]
    SECRET_MQTT_PASSWORD: ENC[AES256_GCM,data:BrILBJVj0cuduBedVII=,iv:krYu9lzkZpCPCZK4wIVi+ieOzNFhLQDhSXYp51TcPjY=,tag:+w8rY9+razgFbhNVOS/KXg==,type:str]
    SECRET_RING_TOKEN: ENC[AES256_GCM,data:NT4uDraus8JLkTGmbQS736WygcguVUUjfXvoUNfpggag9GcMFJLWk93b0JljijXzqIUXERByubeWzi/qbwv+RK5jnEZhqelyfwf8cO8MmZU6so+aRs3wZQlufAGWr9YpNmwBJEheiEecO312ANyIsG+UJyET8nQ84Uot02Wy0A3tTBeLvJlcrjTf1fgGaen6AtQBzXj4sT6mJiFRSxRe9REwfpRBAJ2yMXF6NmJcJylb74xnbgPhy+8+MNlXJwJsjI9mJIGnTUZbfCM2p9INgol+150CKG5lll/FNy97plLIhmAn90phH1Ho4ohGglCaJ6cBYizZcGFLATZ25bE3TD0jnNQIc7Shu+rHASbxchDG935NfB+sM1nQmACzFvUYNrg+RTJlO2NUjOPzjG2KyKDmpzWdwedE3bdFN+zvTefu7SU6CW2EoAJ1aQKwE0IEL2NJCXpumj1zIaaez/bzD6DftLT4GRqw2LnKWlQeFEpVvK0J7BZPJU9DWKPsIQLVykFMSIILDdu3VhDOLwVaNyypJSgLLHyfYkqyx/ya7cl0iSk+NmUF8zgytj9NxYjLget1g75+rxTeN59k4C6Lei2jWfJTxAa3X2CVes68vg7eDrp28O+FxmTL+RtvB/JLQycqS5TiG/HOBxEDliohw5CANz9fzD2n6dIewU48eGu41/bfzu/UXeJbWM7ZMlJITA==,iv:0uZ0jF4JDdA7EAYqccjx2pny7JaAiVqmeKIkG+XIUm0=,tag:L5IEboai3kk5cCFtodDIPw==,type:str]
    SECRET_QB_USERNAME: ENC[AES256_GCM,data:lk+YosDls6r0DN5lRvBch3yrRACo,iv:ByH4fq6NuX152530uwSJyoF4sQ+Mo34KUObm5LDkTB4=,tag:Krsu/rY88WM+Hir3t5TW/Q==,type:str]
    SECRET_QB_PASSWORD: ENC[AES256_GCM,data:cjPxX070FiJYYJeM9eekNf9/V9DG,iv:VLfzRFTcoiMmL2cPQi39rAcQPj84CW2IHj74K66RJmM=,tag:E+bPWw24L+b30V5K8qf7YA==,type:str]
    SECRET_AUTHENTIK_KEY: ENC[AES256_GCM,data:EuONOfXFNtAtDD3Rzw40GBG1wjqwFai8iprlsw48lhHcStUzuAfxVe4FcqEjpVHx1Lo=,iv:nQaRF3TiaKRntZW68wRYp8LfqcuK3onXNVYLz9IaAkw=,tag:rh5RzeeAZ0kDpkJkmo8fzQ==,type:str]
    SECRET_AUTHENTIK_POSTGRES_PASS: ENC[AES256_GCM,data:9XFLmSSwKAkW65Y19p2gMTjKgqy4mJZ4EkXYRU8kXg5A4N1r40yJiBYijQuZQISsTrw=,iv:uXq1Dv6I+0Wp8U42u1/2ivA8rCAYXdCbZ+iuMsCrLpw=,tag:CK6ecx+VSQ7dtuAAHkjGYw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age179qz74lpav0lcywkjzujhnlu3ukq9kgz9jdxm2u59w47j337kc2q0e8q20
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNRkNKcUlFZTBtWWxXRWcx
            MUhoYWcvSFNhY2s5RVVHT3VhRnlOMHdkaGo0Ck8weWV0LyswODJmTGtqaW51dk96
            UWN6K0o3R09Pb05WZXNZOHl0UFNnUHcKLS0tIFJvTWh4aXpFN2Rqc21aaStMTkYy
            QjZaa1ZvOHlSR3I3bktMK2FsSWEyRTAK+kYnE0T9/Gc+Eq6HZAa4WXSIEJAJDEHg
            UweDOtcPQKo8Xe7gvabyrYYbF/G98TAMofdTD31n4xg1VxRAMtK1CA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-07T19:04:05Z"
    mac: ENC[AES256_GCM,data:3NT9uqRr4qzUPq0nUbG7/Gc8USH6dbgnxpWloQE3UShtSoWPRxDBRMVCz/Oa54VWxmd1D9JndpRpx7Xe0QHIjdoioeDOdwF48uNsBWsyrHx/Bqca+etMfxlyHLb/WWDphwAtMwYr9SiOtAv341J6NKt9uBacDmJ3jL1FOSGzeBk=,iv:gm5kJlS9wvS0maTRVKCr7qzRwvKSyvvOrsrlHXhcU3w=,tag:/CQ6LQssaeWnTtO1CaX6cA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
