---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/Chicago"
  METALLB_LB_RANGE: 10.1.10.201-10.1.10.225
  METALLB_TRAEFIK_ADDR: 10.1.10.200
  SVC_MOSQUITTO_ADDR: 10.1.10.230
  SVC_BLOCKY_ADDR: 10.1.10.210
  SVC_PLEX_ADDR: 10.1.10.202
  EXT_CYBERPOWER_PDU_0_ADDR: 10.1.0.197
  EXT_UNIFI_ADDR: 10.1.0.1
  EXT_HUE_BRIDGE_0_ADDR: 10.1.88.193
  EXT_STONE_MAAS_ADDR: 10.1.10.99
