---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_LB_RANGE: 10.1.10.201-10.1.10.225
  METALLB_TRAEFIK_ADDR: 10.1.10.200
  SVC_MOSQUITTO_ADDR: 10.1.10.230
  SVC_BLOCKY_ADDR: 10.1.10.210
  EXT_CYBERPOWER-PDU-0_ADDR: 10.1.0.197
