# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: prowlarr
    namespace: media
type: Opaque
stringData:
    PROWLARR__API_KEY: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age179qz74lpav0lcywkjzujhnlu3ukq9kgz9jdxm2u59w47j337kc2q0e8q20
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4SkRZZlgxMmpQZndYR0NF
            Mzh0cDRZSEUwWlB3M1c1blQwaTVtQ3RBdFNNCnhEeEpnb3NFZU5KUlUrZ3RSaUtJ
            VXQ2UEZvcjVIRGJVSTNPWFcrQ2R0SWMKLS0tIGZhaGZYUGRIOWp6RndJY2dvY2Qx
            TW1obDcrbGI2eHlrZmJyWEVFWGhWNUUKWO8izLMeru5D2C8NHWkxrw9ydl7738eV
            8cgTfU+nhsYRjLg/llBCtJV8zAhcvd3lyawwaUOrYipOmLERxn5FPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-08T03:39:48Z"
    mac: ENC[AES256_GCM,data:WpaDD261OepaLIFvFRRcfqPa6eK2hq66mJPQYFnkoA5Pv+iii8NkdBzZ6bDApsSvMHXdAj/8Wb6t3u2YvKaRLiIw2cru9pAWA4a0o6rVz0VMLXKul4qBprjZcjP657LBHKyd2rr9CXKOJB+Laes2QR7teHLarmNcCtz3fsVSsIg=,iv:4pVbQp8seDTrkCLRsC8zgKgdsWild7HL57S5nZSSwvQ=,tag:f88ioDmfSQ8oSjwJmGfo1g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
