---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: trash-updater
  namespace: media
spec:
  schedule: "*/2 * * * *"
  concurrencyPolicy: "Forbid"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 5
  jobTemplate:
    metadata:
      annotations:
        botkube.io/disable: "true"
    spec:
      backoffLimit: 3
      ttlSecondsAfterFinished: 300
      template:
        metadata:
          annotations:
            botkube.io/disable: "true"
        spec:
          restartPolicy: Never
          containers:
            - name: trash-updater-sonarr
              image: ghcr.io/sob/trash-updater:latest
              imagePullPolicy: Always
              env:
                - name: DOTNET_SYSTEM_GLOBALIZATION_INVARIANT
                  value: "1"
              command:
                - "bin/sh"
                - "-ec"
                - |
                  #/bin/sh

                  set -o nounset
                  set -o errexit

                  cd /tmp
                  curl --location https://github.com/rcdailey/trash-updater/releases/latest/download/trash-linux-x64.zip --output ./trash.zip
                  unzip trash.zip
                  chmod 755 trash
                  ./trash sonarr --config /opt/trash.yaml
              volumeMounts:
                - name: config
                  mountPath: /opt/trash.yaml
                  subPath: trash.yaml
                  readOnly: true
          volumes:
            - name: config
              configMap:
                name: trash-updater-config
