# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: sonarr
    namespace: media
type: Opaque
data:
    SONARR__API_KEY: null
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age179qz74lpav0lcywkjzujhnlu3ukq9kgz9jdxm2u59w47j337kc2q0e8q20
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBudC85WlVITU9TYjJzQnZH
            aGRXR2FobDIwRUova2pCOXlBVjBzb2U5V3pRCmZTM0R4TW91SUxLMzhIRXBOLzdj
            bDVhVEpNb05aVFJod0IxR3Rsdll3SFkKLS0tIGVEcW12ZUUxdTdxS2Z3eHA4bzhY
            bUdZcTNwaC95ZXZFdjQ1ZEhWWmdzMGMK3rtbhFs6PgJJFrHVhSChmRkQbkrux2KH
            0B3o+83GxcmNsVCWR9VL4d+woxN/xK8plqJvJokMy6DO8IGwphqzhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-05T19:23:39Z"
    mac: ENC[AES256_GCM,data:ZqAIgZwC7P+RXm3FAyE3xSiAhmbN1lGK5NEW3kJWon9auiGntvXXTJDIRh1fxth1eQDxFQ/4NsBUlNCtl4gQAeZ/VO4pMR9dPmav2DwiHXYdsYg6MFucGVX7jltcS44fgo3JLT6er2bC0qnPGn3OrelSB89utWfaNAKzLdWM7Uw=,iv:AQFQum6Wdzooz8VPKgVZ0xSVI+HrW7VxUPluMH8g4hA=,tag:FoVrgJtakDTjs4SO95V2UA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
