# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: sonarr
    namespace: media
type: Opaque
data:
    SONARR__API_KEY: ENC[AES256_GCM,data:uAlzQr9If7e+vvnoR8hCo3ERA0GsP2M=,iv:BaqBjPQn5j/fXt00AiPoGLjWAnaSJES20+hZpmeD2jI=,tag:9eD/Aq+akZN2Oza42ghO7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age179qz74lpav0lcywkjzujhnlu3ukq9kgz9jdxm2u59w47j337kc2q0e8q20
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBudC85WlVITU9TYjJzQnZH
            aGRXR2FobDIwRUova2pCOXlBVjBzb2U5V3pRCmZTM0R4TW91SUxLMzhIRXBOLzdj
            bDVhVEpNb05aVFJod0IxR3Rsdll3SFkKLS0tIGVEcW12ZUUxdTdxS2Z3eHA4bzhY
            bUdZcTNwaC95ZXZFdjQ1ZEhWWmdzMGMK3rtbhFs6PgJJFrHVhSChmRkQbkrux2KH
            0B3o+83GxcmNsVCWR9VL4d+woxN/xK8plqJvJokMy6DO8IGwphqzhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-08T16:37:49Z"
    mac: ENC[AES256_GCM,data:tEmjsUjq13q7m0V9gRWPlDN/EwtfuiMvOmoPluw9KiCud+htI7E37UO1wkc7vvHlXuL20UzqqqvPFWRe9cet0GU0Df3/uwXruD2xBYOigvcOWlZYgp0GCUQ9FVJnobwfYZOKTeyfWRwiCmiHtYgQNn9iZn+X1bf6Ng8mU8CtSX4=,iv:lNkyA6Adt7YWRuHy8ERMVdJIptmKveu7rBUDo2HaW6U=,tag:86/O0HCInrzgX6TBvuJnRw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
