---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postal
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: /charts/kah-common/
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 5m
    dependencies:
      - name: mariadb
        version: 10.2.0
        repository: https://charts.bitnami.com/bitnami
  values:
    fullnameOverride: postal
    image:
      repository: ghcr.io/postalserver/postal
      tag: 2.1.0
    env:
      POSTAL_CONFIG_ROOT: /config
      KATAPULT_CONFIG_FILE: /config.yaml
      WAIT_FOR_TIMEOUT: 90
        # WAIT_FOR_TARGETS: |-
        # mariadb:3306
        # rabbitmq:5672
    service:
      main:
        ports:
          http:
            port: 5000
      smtp:
        ports:
          smtp:
            port: 25
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          hajimari.io/enable: "true"
          hajimari.io/icon: "resistor-nodes"
          hajimari.io/group: "automation"
        hosts:
          - host: "postal.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "postal.${SECRET_DOMAIN}"
            secretName: postal-tls
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 750Mi
