---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postal-mariadb-v1
  namespace: networking
  labels:
    kasten.io/backup-volume: "enabled"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ceph-block
