---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: ring-mqtt
  name: ring-mqtt
  namespace: home
spec:
  ports:
    - name: "8554"
      port: 8554
      targetPort: 8554
  selector:
    io.kompose.service: ring-mqtt
