---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flood-config-v3
  namespace: media
  labels:
    kasten.io/backup-volume: "enabled"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-block
