---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flood
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: flood
      version: 6.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 15m
  values:
    image:
      repository: jesec/flood
      tag: 4.7.0
    env:
      FLOOD_OPTION_RUNDIR: /config
      FLOOD_OPTION_AUTH: "none"
      FLOOD_OPTION_RTSOCKET: "/tmp/rtorrent.sock"
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          external-dns/is-public: "true"
          hajimari.io/enable: "false"
          hajimari.io/icon: "cloud-download"
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
          - host: torrent.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
              - torrent.${SECRET_DOMAIN}
    persistence:
      data:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "10.1.0.104"
            path: /Media/Downloads/rtorrent
      config:
        enabled: true
        existingClaim: flood-config-v1
      socket:
        enabled: true
        type: emptyDir
        # medium: Memory
        mountPath: /tmp
    resources:
      requests:
        memory: 50Mi
        cpu: 50m
      limits:
        memory: 640Mi
    additionalContainers:
      - name: rtorrent
        # image: billimek/alpine-rtorrent:0.9.8-1
        image: billimek/rtorrent:latest
        env:
          - name: TZ
          - name: PUID
            value: "1001"
          - name: PGID
            value: "1001"
        ports:
          - name: bt
            containerPort: 49161
            protocol: TCP
        resources:
          limits:
            memory: 1Gi
          requests:
            cpu: 50m
            memory: 200Mi
        tty: true
        volumeMounts:
          - mountPath: /config
            name: config
          - mountPath: /data
            name: data
          - mountPath: /session
            name: data
            subPath: .session
          - mountPath: /watch
            name: data
            subPath: watch
          - mountPath: /download
            name: data
            subPath: torrents
          - mountPath: /socket
            name: socket
    service:
      bt:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: ${METALLB_FLOOD_RTORRENT_ADDR}
        ports:
          bt:
            enabled: true
            port: 49161
            protocol: TCP
