---
- name: Install filesystem tools
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: true
  with_items:
    - "{{ ubuntu_filesystem_packages | join (',') }}"

- name: configure smartd
  ansible.builtin.copy:
    dest: /etc/smartd.conf
    mode: 0644
    content: |
      DEVICESCAN -a -o on -S on -n standby,q -s (S/../.././02|L/../../6/03) -W 4,35,40
  notify: restart smartd

- name: increase max_user_watches
  ansible.posix.sysctl:
    name: fs.inotify.max_user_watches
    value: "524288"
    state: present
    sysctl_file: /etc/sysctl.d/98-kubernetes-fs.conf

- name: increas max_user_instances
  ansible.posix.sysctl:
    name: fs.inotify.max_user_instances
    value: "512"
    state: present
    sysctl_file: /etc/sysctl.d/98-max_user_instances.conf

- name: Disable swap at runtime
  ansible.builtin.command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Disable swap on boot
  ansible.posix.mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  loop:
    - swap
    - none
