---
- name: remove curtin proxy info
  ansible.builtin.file:
    state: absent
    path: /etc/apt/apt.conf.d/90curtin-aptproxy

- name: install common packages
  ansible.builtin.apt:
    name: "{{ item }}"
    install_recommends: false
    autoclean: true
    autoremove: true
  with_items:
    - "{{ ubuntu_common_packages | join (',') }}"

- name: disable apt recommends
  ansible.builtin.blockinfile:
    path: /etc/apt/apt.conf.d/10-no-recommends
    mode: 0644
    create: true
    block: |
      APT::Install-Recommends "false";
      APT::Install-Suggests "false";
      APT::Get::Install-Recommends "false";
      APT::Get::Install-Suggests "false";

- name: gather installed packages
  ansible.builtin.package_facts:
    manager: auto

- name: remove packages
  block:
    - name: check if snap is installed
      ansible.builtin.debug:
        msg: "snapd is installed"
      register: snapd_check
      when:
        - "'snapd' in ubuntu_common_packages_remove"
        - "'snapd' in ansible_facts.packages"

    - name: remove snap packages
      ansible.builtin.command: snap remove {{ item }}
      loop:
        - lxd
        - core18
        - core20
        - snapd
      when:
        - "'snapd' in ubuntu_common_packages_remove"
        - "'snapd' in ansible_facts.packages"
        - snapd_check.failed is defined

    - name: remove packages
      ansible.builtin.apt:
        name: "{{ ubuntu_common_packages_remove }}"
        state: absent
        autoremove: true

    - name: remove files
      ansible.builtin.file:
        state: absent
        path: "{{ item }}"
      loop:
        - "/home/{{ ansible_user }}/.snap"
        - "/snap"
        - "/var/snap"
        - "/var/lib/snapd"
        - "/var/cache/snapd"
        - "/usr/lib/snapd"
        - "/etc/cloud"
        - "/var/lib/cloud"
      when:
        - "'snapd' in ubuntu_common_packages_remove"
        - "'cloud-init' in ubuntu_common_packages_remove"
  when:
    - ubuntu_common_packages_remove is defined
    - ubuntu_common_packages_remove is iterable
    - ubuntu_common_packages_remove | length > 0

- name: Copy 20auto-upgrades unattended-upgrades config
  ansible.builtin.blockinfile:
    path: /etc/apt/apt.conf.d/20auto-upgrades
    mode: 0644
    create: true
    block: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Download-Upgradeable-Packages "1";
      APT::Periodic::AutocleanInterval "7";
      APT::Periodic::Unattended-Upgrade "1";

- name: Copy 50unattended-upgrades unattended-upgrades config
  ansible.builtin.blockinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    mode: 0644
    create: true
    block: |
      Unattended-Upgrade::Automatic-Reboot "false";
      Unattended-Upgrade::Remove-Unused-Dependencies "true";
      Unattended-Upgrade::Allowed-Origins {
          "${distro_id} stable";
          "${distro_id} ${distro_codename}-security";
          "${distro_id} ${distro_codename}-updates";
      };

- name: Start unattended-upgrades service
  ansible.builtin.systemd:
    name: unattended-upgrades
    enabled: true
    state: started

- name: Restart unattended-upgrades service
  ansible.builtin.service:
    name: unattended-upgrades.service
    daemon_reload: true
    enabled: true
    state: restarted
