apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - default
  - home
  - kasten
  - kube-system
  - media
  - monitoring
  - networking
  - rook-ceph
  - system-upgrade
  - teslamate
