---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sabnzbd
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: sabnzbd
      version: 9.4.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    image:
      repository: ghcr.io/k8s-at-home/sabnzbd
      tag: v3.6.0
    env:
      TZ: "${TIMEZONE}"
      HOST_WHITELIST_ENTRIES: >-
        sabnzbd,
        sabnzbd.media,
        sabnzbd.media.svc,
        sabnzbd.media.svc.cluster,
        sabnzbd.media.svc.cluster.local,
        sabnzbd.${SECRET_DOMAIN}
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          hajimari.io/enable: "true"
          hajimari.io/icon: "download-box"
        hosts:
          - host: "sabnzbd.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "sabnzbd.${SECRET_DOMAIN}"
            secretName: sabnzbd-tls
    podSecurityContext:
      supplementalGroups:
        - 100
    persistence:
      config:
        enabled: true
        existingClaim: sabnzbd-config-v1
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "10.1.0.104"
            path: /Media
        mountPath: /media
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 7500Mi
