---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: sabnzbd-http
  namespace: media
spec:
  jobName: sabnzbd-http
  interval: 1m
  scrapeTimeout: 5s
  module: http_2xx
  prober:
    url: blackbox-exporter.monitoring:9115
  targets:
    staticConfig:
      static:
        - "http://sabnzbd.media:8080"
        - "https://sabnzbd.${SECRET_DOMAIN}"
