# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: sabnzbd
    namespace: media
type: Opaque
data:
    SABNZBD__API_KEY: null
    SABNZBD__NZB_KEY: null
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age179qz74lpav0lcywkjzujhnlu3ukq9kgz9jdxm2u59w47j337kc2q0e8q20
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBudC85WlVITU9TYjJzQnZH
            aGRXR2FobDIwRUova2pCOXlBVjBzb2U5V3pRCmZTM0R4TW91SUxLMzhIRXBOLzdj
            bDVhVEpNb05aVFJod0IxR3Rsdll3SFkKLS0tIGVEcW12ZUUxdTdxS2Z3eHA4bzhY
            bUdZcTNwaC95ZXZFdjQ1ZEhWWmdzMGMK3rtbhFs6PgJJFrHVhSChmRkQbkrux2KH
            0B3o+83GxcmNsVCWR9VL4d+woxN/xK8plqJvJokMy6DO8IGwphqzhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-05T19:29:15Z"
    mac: ENC[AES256_GCM,data:GYVD7dFLt9vX+gFarVKNt5QKt0GxhNnDlzJP5zZWIUZ7WSWSmD/LdBbECpGMdWuOnqqaKOa5pGKSBkBttSfb3CLjzHNPtbIMuJooJQ+eq33+IgAEHeRh5KFIFrHzyaHxf+260BePrIln67+XWaX6VFClCOgHfqmRGj+5rAXF/fo=,iv:R/NVi7hXHEe+CaW4stdAvmsisMv4awNWZy0yT114iEU=,tag:u32UljHJDFLAXBl2DpJTaQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
