# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: sabnzbd
    namespace: media
type: Opaque
stringData:
    SABNZBD__API_KEY: ENC[AES256_GCM,data:R/jzqPL2OuqVNFtc04zV5ZPoO1HsidnTiA==,iv:dSM/xp9loytLXW0v9UXREOnBx0DD2QToEeWx9Jyk5lk=,tag:N9xObN+txgGeQ+QU2bjcBA==,type:str]
    SABNZBD__NZB_KEY: ENC[AES256_GCM,data:b+i5NCPUhye12QeGfjzwvKvL5oeZUUYw0A==,iv:ipfxtP8KIJxhmbr2ep41V77ZjiUjiUUGH3j1g5Z7QBE=,tag:dF5S2EszebuTtnQhit0aWw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age179qz74lpav0lcywkjzujhnlu3ukq9kgz9jdxm2u59w47j337kc2q0e8q20
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBudC85WlVITU9TYjJzQnZH
            aGRXR2FobDIwRUova2pCOXlBVjBzb2U5V3pRCmZTM0R4TW91SUxLMzhIRXBOLzdj
            bDVhVEpNb05aVFJod0IxR3Rsdll3SFkKLS0tIGVEcW12ZUUxdTdxS2Z3eHA4bzhY
            bUdZcTNwaC95ZXZFdjQ1ZEhWWmdzMGMK3rtbhFs6PgJJFrHVhSChmRkQbkrux2KH
            0B3o+83GxcmNsVCWR9VL4d+woxN/xK8plqJvJokMy6DO8IGwphqzhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-08T16:35:16Z"
    mac: ENC[AES256_GCM,data:cAsrDyD0mmA8wJA9Dkrhejqlqow4xb4C3G+P10V2x+PtQvqbcUQ42vCctfnJrGjOent6EyXWPBr8fH0dh65xv+90s3ugjdYWN84JhQFXMuvcsOSdzIp+SlwNhFkB+hBkJfCTVwoXE8iCfa+i2cZn95nN9lJHmKiWt5nbzsGPu/4=,iv:rGSg36QenXKs7OERFSMLQ6kqigXtTTsJzvE1atx2/uA=,tag:jMK+X/N3rUZ1wJbiteblUA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
