---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "unifi"
  namespace: external
spec:
  ports:
    - name: "http"
      protocol: "TCP"
      port: 80
      targetPort: 80
      nodePort: 0
selector: {}
---
apiVersion: "v1"
kind: "Endpoints"
metadata:
  name: "unifi"
  namespace: external
subsets:
  - addresses:
    - ip: "${EXT_UNIFI_ADDR}"
    ports:
      - port: 80
        name: "http"
