---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-lobby-data-v1
  namespace: gaming
  labels:
    kasten.io/backup-volume: "enabled"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ceph-block
