---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft-bedrock
  namespace: gaming
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://itzg.github.io/minecraft-server-charts/
      chart: minecraft-bedrock
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: flux-system
      interval: 5m
  values:
    persistence:
      storageClass: "rook-ceph-block"
      dataDir:
        enabled: true
        Size: 10Gi
    resources:
      requests:
        memory: 250Mi
        cpu: 100m
      limits:
        memory: 250Mi
    podAnnotations:
      backup.velero.io/backup-volumes: datadir
    minecraftServer:
      eula: "TRUE"
      version: "LATEST"
      difficulty: normal
      gameMode: creative
      ops: "2535432067443552"
      levelName: world
      serverName: "\u00a79STONEHEDGES \u00a7c\u00a7lSMP\u00a7c\u00a7l\u00a7k!"
      cheats: true
      serviceType: LoadBalancer
