---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft-creative
  namespace: gaming
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://itzg.github.io/minecraft-server-charts/
      chart: minecraft
      version: 4.13.0
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: flux-system
      interval: 5m
  values:
    image: itzg/minecraft-server
    imageTag: java17
    strategyType: Recreate
    persistence:
      dataDir:
        enabled: true
        existingClaim: minecraft-creative-data-v1
    resources:
      requests:
        memory: 6Gi
        cpu: 250m
      limits:
        memory: 7Gi
    livenessProbe:
      initialDelaySeconds: 30
      periodSeconds: 5
      failureThreshold: 10
      successThreshold: 1
      timeoutSeconds: 1
    readinessProbe:
      initialDelaySeconds: 30
      periodSeconds: 5
      failureThreshold: 10
      successThreshold: 1
      timeoutSeconds: 1
    startupProbe:
      enabled: true
      failureThreshold: 30
      periodSeconds: 10
    podAnnotations:
      backup.velero.io/backup-volumes: datadir
    extraEnv:
      ENABLE_AUTOPAUSE: FALSE
    minecraftServer:
      eula: "TRUE"
      version: "LATEST"
      type: PAPER
      forceReDownload: true
      jvmOpts: "-Xms6G -Xmx6G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true"
      memory: 6144M
      difficulty: normal
      maxTickTime: -1
      serviceType: LoadBalancer
      gameMode: creative
      motd: "\u00a7fstonehedges\u00a7 - \u00a7a\u00a7lcreative\u00a7"
      icon: https://www.freeiconspng.com/uploads/minecraft-server-icon-13.png
      rcon:
        enabled: false
        port: 25575
        password: "mc-rcon"
        serviceType: LoadBalancer
      extraPorts:
        - name: map
          containerPort: 8123
          service:
            enabled: true
            type: ClusterIP
            port: 8123
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: traefik
            hosts:
              - name: minecraft.56kbps.io
                path: /
            tls:
            - hosts:
              - minecraft.56kbps.io
