---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft-proxy
  namespace: gaming
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://itzg.github.io/minecraft-server-charts/
      chart: minecraft-proxy
      version: 2.5.0
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: flux-system
      interval: 5m
  values:
    image: itzg/bungeecord
    imageTag: 2021.4.0-java11
    securityContext:
      # Security context settings - need to use root or else there will be problems due to the underlying image trying to do some things as root already
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0
    resources:
      requests:
        memory: 250Mi
        cpu: 50m
      limits:
        memory: 500Mi
    podAnnotations:
      configmap.reloader.stakater.com/reload: "minecraft-proxy-minecraft-proxy-config"
    extraEnv:
      SPIGET_PLUGINS: "78915,75"
    minecraftProxy:
      type: WATERFALL
      # A list of .jar URLs to download into the plugins folder.
      # plugins: []
      serviceType: LoadBalancer
      loadBalancerIP: 10.0.6.106
      externalTrafficPolicy: Local
      # externalIPs:
      # This can be set to the contents of your config file (only works with yaml currently)
      config: |
        player_limit: -1
        ip_forward: true
        permissions:
          default:
          - bungeecord.command.server
          - bungeecord.command.list
          - alert.trigger
          - slashserver.lobby
          - slashserver.survival
          - slashserver.survival2
          admin:
          - bungeecord.command.alert
          - bungeecord.command.end
          - bungeecord.command.ip
          - bungeecord.command.reload
          - alert.receive
          - alert.receive.firstjoin
          - alert.command.toggle
          - alert.command.reload
          family:
          - bungeecord.server.survival
        timeout: 30000
        log_pings: true
        log_commands: false
        online_mode: true
        servers:
          lobby:
            motd: '&1eviljungle lobby'
            address: minecraft-lobby-minecraft:25565
            restricted: false
          creative:
            motd: 'creative server'
            address: mc-minecraft:25565
            restricted: false
          survival:
            motd: 'Private Survival SMP'
            address: mcsv-minecraft:25565
            restricted: true
          survival2:
            motd: 'Public Survival EZ-mode SMP'
            address: mcsv2-minecraft:25565
            restricted: false
        listeners:
        - query_port: 25577
          motd: '&3eviljungle &6&Llobby'
          priorities:
          - lobby
          bind_local_address: true
          tab_list: GLOBAL_PING
          query_enabled: true
          host: 0.0.0.0:25577
        ping_passthrough: true
        groups:
          ruqkus:
          - admin
          - family
          DottyParrot:
          - family
      #    forced_hosts:
      #      pvp.md-5.net: pvp
      #    max_players: 1
      #    tab_size: 60
      #    force_default_server: false
      #    proxy_protocol: false
      #  disabled_commands:
      #  - disabledcommandhere
      #  network_compression_threshold: 256
      #  groups:
      #    md_5:
      #    - admin
      #  connection_throttle: 4000
      #  connection_throttle_limit: 3
      #  stats: f2876aa6-74d2-468c-90ee-1377111f1c9f
      #  forge_support: false
      #  inject_commands: false