---
ubuntu_filesystem_packages:
  - gdisk
  - hdparm
  - lvm2
  - nfs-common
  - nvme-cli
  - open-iscsi
  - smartmontools
  - socat

ubuntu_network_packages:
  - arptables
  - ebtables
  - iputils-ping
  - ipvsadm
  - net-tools

ubuntu_common_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - psmisc
  - software-properties-common
  - unattended-upgrades
  - htop
  - unzip

ubuntu_common_packages_remove:
  - apparmor
  - apport
  - byobu
  - cloud-init
  - cloud-guest-utils
  - cloud-initramfs-copymods
  - cloud-initramfs-dyn-netconf
  - friendly-recovery
  - landscape-common
  - lxd-agent-loader
  - ntfs-3g
  - plymouth
  - plymouth-theme-ubuntu-text
  - popularity-contest
  - snapd
  - sosreport
  - ubuntu-advantage-tools
  - ufw
