# yamllint disable
# values.yaml: |
#   env:
#     SERVER_PASS: ${VALHEIM_SERVER_PASSWORD}
#     SUPERVISOR_HTTP_PASS: ${VALHEIM_SUPERVISOR_PASSWORD}
#
kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: valheim-helm-values
    namespace: gaming
stringData:
    values.yaml: ENC[AES256_GCM,data:I+oNpYePkAYMyFi8x3dNmfZVbOlHhGx5ym2J0EzZkTX+BO8baLZ396o6IGu5gvvnJQIaAuAz6CUYbmFfxie3Z6+kvHmSXYj0UP2v4ZJ5i+6xgAM5UgWmBoKuV2/9cxPOU8Yn054H,iv:nLGG+t+VLkcxdVjszfki6AlQf1t7jiYYJ00oclXJgB0=,tag:gwYGDme/BjOQfJR50GNKRQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age179qz74lpav0lcywkjzujhnlu3ukq9kgz9jdxm2u59w47j337kc2q0e8q20
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHU2E5eEMzNEhJOTU3dVhK
            aEUrZzJSRExaQmg1T2x4OVBUU3VucXZicDNRCit5SDNRcEszWXQ5R0ZFb2g3Y0M2
            T2pqYTVWQXVNSjZTVkdSeVJVVVhrd1kKLS0tIE5IaitranFjcjMzNzZoR1FGRldr
            WjNzUDJFNFJJUGd4VkdWTFhJdDVXN3MKN07j2TL+jcCmnIgIn9HW0xHMVGYuaIxG
            1CqDj9uKR5P+CvBUpz25FDnScq+oi+zo5e7xF6GrZklLCj5vkbsbUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-18T23:45:35Z"
    mac: ENC[AES256_GCM,data:yCZ+IBlSCTnmrnbqSYh1+kF4smd5inb0YWFTEhQjNg0jfaeSbeX43wNGjTE2JMA9D4HnFCIwbWmwfjjl9/BglT+yU+es8SeQKh4SVeOx1hH4Bw4MoDuYIqJLZIuyH1URAl4Bj3h9YklD5PAttogtDKJF4LVIzCBA9E5j4nLQac4=,iv:mrAbZRhcN/MWSlvI7YpKZ7T+3Wp7TOI+tswDpau4ZU4=,tag:uWGKhyyuyS7jkwPgTVCmzg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
