---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bazarr
  - flood
  - media-browser
  - overseerr
  - photoprism
  - plex
  - prowlarr
  - radarr
  - radarr-uhd
  - readarr
  - recyclarr
  - sabnzbd
  - sonarr
  - sonarr-uhd
  - tautulli
