---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app theme-park
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: kah-common-chart
      version: 1.2.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    global:
      nameOverride: *app
    controller:
      replicas: 3
      strategy: RollingUpdate
    image:
      repository: ghcr.io/onedr0p/theme-park
      tag: 1.13.1@sha256:0916d776425b39d7804ab883ebfa57ec4bd9781d4f4cafb8f4eb13685728d38d
    service:
      main:
        ports:
          http:
            port: 8080
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          external-dns.home.arpa/enabled: "true"
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: *app
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        memory: 150Mi
