# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:hS2VJR4xRQ3tEUlOr5qVt7FFJmDOn25M1G+S/H9RZk5RNlixfw==,iv:4/SVjLKiMbYBiQ1jG0Tj0K+5xykdCslEzA4iJaK0+S8=,tag:VEM/uos3XPC/gRiTnp1FrQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age179qz74lpav0lcywkjzujhnlu3ukq9kgz9jdxm2u59w47j337kc2q0e8q20
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1WDBRZ3F0VVRjdmJBM0ZZ
            Q0Nwd0ZrZXV6aUxJTG5jLzJkblM1TmVlVVRFCkdoRC9tWmhkRkJTTW55cFVQdHlJ
            Y2xqa0ZFQzg0VGVMMHJaenZJTm5FSUEKLS0tIHpEZ093YmpCd25tT0lGVW0vc1p3
            WmtJYWpPeVIvOGhkaFhjbmYyUHViZ0EKa28PdF6mrnSHxE/O7OX77QqT4LgsflAT
            OsJev44ZPwEKdnM+DzNIOXIBPSKfRQ1TyBlv0di46D4Y+KA6fDP9pQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-31T19:27:20Z"
    mac: ENC[AES256_GCM,data:WkDZ8J0dpOga4puzonGqb8PSB5bNVRenBp93WTB1GyQhvrOlWYKKdA9SYjFP1QTd7xGZ2F6tkpJqixXMUzOtCRvLTvYOt1T/J9w7DWM9wytg1VSo1EvFV1mUhVhWThpoZX5vQ9KfqJjHNj36Dn499GonQ9Z2uACgXaG6TMSv7jk=,iv:6dyPetff6i6d0NY99z9WQX6EiLhRENb6mAfO65+Xics=,tag:jyJxxub2YJNTJzQ3N8XQ2A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
