---
apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: monitoring
  name: uptimerobot-heartbeat
spec:
  schedule: "* * * * *"
  concurrencyPolicy: "Forbid"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 5
  jobTemplate:
    metadata:
      annotations:
        botkube.io/disable: "true"
    spec:
      backoffLimit: 3
      ttlSecondsAfterFinished: 300
      template:
        metadata:
          annotations:
            botkube.io/disable: "true"
        spec:
          restartPolicy: Never
          containers:
            - name: uptimerobot-heartbeat
              image: ghcr.io/k8s-at-home/kubectl:v1.23.1
              envFrom:
                - secretRef:
                    name: uptimerobot-heartbeat-url
              command:
                - "/app/uptimerobot-heartbeat.sh"
              volumeMounts:
                - name: uptimerobot-heartbeat
                  mountPath: /app/uptimerobot-heartbeat.sh
                  subPath: uptimerobot-heartbeat.sh
                  readOnly: true
          volumes:
            - name: uptimerobot-heartbeat
              projected:
                defaultMode: 0775
                sources:
                  - configMap:
                      name: uptimerobot-heartbeat
                      items:
                        - key: uptimerobot-heartbeat.sh
                          path: uptimerobot-heartbeat.sh
