# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: uptimerobot-heartbeat-url
    namespace: monitoring
stringData:
    UPTIMEROBOT_HEARTBEAT_URL: ENC[AES256_GCM,data:+bPnEuUFj8z0geSgGE6B7YsoK70RpypC+UscqE7vaOiMo7YKqJorZWIio/JXDG0o0bdEcQh52W6uu8FIVR0pDz68pDdzQRtVFU8zQwOxhdf67YxJdw==,iv:Mt4JDSnFgp/oehnFC70uHARK8fSuFmxCKG9LMzBgPpw=,tag:b60qkevavYnCgNkXBzq+QQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age179qz74lpav0lcywkjzujhnlu3ukq9kgz9jdxm2u59w47j337kc2q0e8q20
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhM3lJcjUyTU9GVnVhU3I2
            ZTZkUVI2d2RzRUtFNWM5WDdhRnNrNGtqM0FBClFldlRHWWpRVTF5dHFPTWVnRmY2
            eGhsM3dheEdyUVlyVmFZUU9zY0ZNWmsKLS0tIGZPRGVDaU9OeG9pT3cxNDRGN0tQ
            ZDNNMXhDUzFBQUlvdWQ3NjJHRys4aDQKO+OlU4PzIuW0+jkSiHJFmV/KOaipj5Su
            bZixzlNfGabOb/qJpCRrlkZKA6gIxgBlZyWcR2kE1I+4NYCAAv4QAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-03T16:32:42Z"
    mac: ENC[AES256_GCM,data:EQfaTiz9d6KFdRFpv+5vKHTCOkdnKTegZvfh1Nc1k5ZKRrLTVGHnvfy9ZNJ5TqUVCJiAhxzig1JxJrqF3ZkjrljTZVWY8UBMAU/yIVFpASfzrfBHNs4pvG2qOLn6hOFfY/fnw72mtSzeMxAiwz3flXrH7o6DiJrwSNFjeuz562U=,iv:gjPUCg3Fm8E3qG/uTLT5D3bfr+kcNPoTzcxLwgSUebk=,tag:DAn+ZiNQC/M+IqTqVQAFNQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
