---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freeradius-config-v1
  namespace: networking
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: ceph-block
