---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: freeradius
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: /charts/kah-common/
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 5m
  values:
    fullnameOverride: freeradius
    image:
      repository: docker.io/freeradius/freeradius-server
      tag: 3.0.25-alpine
    env:
      NOAPIBROWSERAUTH: 1
    service:
      main:
        ports:
          main:
            protocol: UDP
            port: 1812
      accounting:
        enabled: true
        ports:
          accounting:
            port: 1813
            protocol: UDP
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
    persistence:
      config:
        enabled: true
        existingClaim: freeradius-config-v1
        mountPath: "/etc/raddb"
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 750Mi
