---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: freeradius
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: /charts/kah-common/
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 5m
  values:
    fullnameOverride: freeradius
    image:
      repository: ghcr.io/truecharts/freeradius
      tag: v3.0.25
    env: {}
    service:
      main:
        type: ClusterIP
        externalTrafficPolicy: Local
        ports:
          main:
            enabled: true
            port: 1812
            protocol: UDP
            targetPort: 1812
      accounting:
        type: ClusterIP
        externalTrafficPolicy: Local
        ports:
          accounting:
            enabled: true
            port: 1813
            protocol: UDP
            targetPort: 1813
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
    persistence:
      config:
        enabled: false
        existingClaim: freeradius-config-v1
        mountPath: "/etc/raddb"
