# yamllint disable
# comm_config.yaml: |
#   communications:
#     slack:
#       enabled: true
#       token:
#       channel:
apiVersion: v1
kind: Secret
metadata:
    name: botkube-communications
    namespace: monitoring
stringData:
    comm_config.yaml: ENC[AES256_GCM,data:xxnG9X6t145MvU1jwiNQVWGC5ev5KEttM/LGPJYgKn/GMJyeXvV7v9+CLZ43sPzb4L04VhPUkL1Rv8odAb4XkkHL55QsY+5qwoMG0mVoLgjwPZWkNdE3HEy9qE0tsTg9YGOAWKt0IKSxN+8quUlYoIY1dZ78go8643kaLfFbrtY+C0fJJ0lh3tbTrlw=,iv:yzx/MSuh/CJFqDKIyoEP42rnSg4Q00iC+HtH3y0jRYw=,tag:b/stjb97MesxUe1lSUoZfA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age179qz74lpav0lcywkjzujhnlu3ukq9kgz9jdxm2u59w47j337kc2q0e8q20
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4bHNOQWFyaU9TL3lyZ3ZG
            VGFET3UxOXZWdVJaQ1g5SVI5TUt1VC8vb1NRCi9Ea0V0eW5Rc0xjNEpDbi84U1Uy
            dkJkU21yeXVSaWYvUTMwMVMvQ3lDYlEKLS0tIFdtVkY5NU41MklTRmdYcHA3WStw
            Y05BRWtJL2dDcHU4Ly9JTzBZTmo5Q0kKk0Pm00TFLSa0NZNctVtM3RQp8iIn/TRG
            2P/ZeMvU8bjGXbEwByhXc8yc0R7EV/ROM2RwYEPwd7YPcuYvkl1VsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-03T17:14:10Z"
    mac: ENC[AES256_GCM,data:8gyom+M7cORfWJoXT0Z5ggyz6iWYfG7Xavv5Gl/k7WgAAIva3WsiXQ5DOW+yTU0GBrhdlXrpifAeHRIVHkaMI+o0pzLNvsRy9TfRtorLQfJCbYHGd+wX9l9TVvGTJX7fD7vHgWnEBO9EJIoEy5Bf3Ah9pqtSRqak+7RfMnvbKhw=,iv:G9cvx/zD3Z1rtnCmhOJe9/fW5Pww9walI0D8EOBCgN0=,tag:oHLNURHiNiEsS+OuDrmKMA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
