---
name: Schedule - Library Chart Update

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  schedule:
    - cron: "0 */4 * * *"

jobs:
  library-chart-update:
    name: Library Chart Update
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: azure/setup-helm@v1
        with:
          version: v3.6.3
      - run: helm repo add k8s-at-home-library https://library-charts.k8s-at-home.com
      - run: helm repo update
      - run: helm dep update
        working-directory: charts/kah-common
      - uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: renovate-k8s-at-home-library-chart
          delete-branch: true
          title: "chore(ci): update k8s-at-home library chart"
          signoff: true
          committer: "Sean O'Brien <sob@users.noreply.github.com>"
          author: "Sean O'Brien <sob@users.noreply.github.com>"
          assigness: "sob"
          commit-message: "chore(ci) update k8s-at-home library chart"
          body: |
            Update the k8s-at-home library chart
          labels: component/ci
